### ISSUE TITLE
Can't switch to tab group with 0 tabs

### ISSUE THREAD

**Issue by RichardDavies** [Drive4ik/simple-tab-groups#1]
If you close all of the tabs in a group and switch to another group, you're unable to return to the group with 0 tabs. You have to expand the group to view the group details and click the "Open new tab" link to create a blank tab in the group before it will let you switch back to that group.

**Comment by Drive4ik** [comment]
This is due to the fact that closing the last tab closes firefox.

**Comment by RichardDavies** [comment]
...Not if you have any pinned tabs. Sorry I forgot to mention that I have several pinned tabs (which aren't considered part of any tab group) so when I close all of the tabs in the current group, the Firefox window doesn't close because the pinned tabs are still open.

**Comment by RichardDavies** [comment]
Also, off topic, but I don't know how else to report it. The Simple Tab Groups extension seems to have mysteriously disappeared from addons.mozilla.org after I installed it just a few hours ago. https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/ results in a Page Not Found error.

**Comment by Drive4ik** [comment]
> ...Not if you have any pinned tabs.

Strangely enough, I also have fixed tabs and there was no such problem on the stable version of firefox. I will test at nightly versions.

> The Simple Tab Groups extension seems to have mysteriously disappeared from addons.mozilla.org after I installed it just a few hours ago. 

This was due to the fact that I used the javascript Vue library (https://vuejs.org/) to speed development. And it in turn uses `eval()`. According to Mozilla Corporation rules, you can not use `eval()` in plug-ins.

> Extensions developed with WebExtension APIs have a Content Security Policy (CSP) applied to them by default. This restricts the sources from which they can load `<script>` and `<object>` resources, and disallows potentially unsafe practices such as the use of `eval()`.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_Security_Policy

At the moment I'm doing the rewriting of the plugin without using third-party libraries (except jQuery). And the plug-in will be available soon

**Comment by Drive4ik** [comment]
Addon is updated.
Please, update it

**Comment by RichardDavies** [comment]
Perfect. Now I can switch to a group with 0 tabs. Thanks for the quick fix!

**Comment by Drive4ik** [comment]
Please, update your review on https://addons.mozilla.org/ru/firefox/addon/simple-tab-groups/reviews/

**Comment by RichardDavies** [comment]
it doesn't look like my review mentioned this bug.
