### ISSUE TITLE
Next / previous group from history hotkeys aren't working

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#1023]
**Describe the bug**
I set keyboard shortcuts for "Next group" and "Previous group" "from history". Clicking the key combinations doesn't work. It used to work (though poorly, sometimes several key presses were necessary before a group would change). Now, I click many times and nothing happens.

**To Reproduce**
1. Go to extention settings
2. Click on the item for "Load next group from history" and set a key combination
3. Click on the item for "Load previous group from history" and set a key combination
4. Try to use the key combinations and notice the group never switches.

**Expected behavior**
The key presses should change the visible group within group display history.

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 20.04 LTS
 - Firefox version: 111.0.1
 - Simple Tab Groups version: 4.8.1

**Comment by SpaceClicker** [comment]
I would like to second this, as I have had the same problem for a while now.  It used to work unreliably before, but now it never works, although I do think I got it to work once since it stopped working all together.

I am using Windows 11 with all other Info the same as OPs.

I would really like the ctrl-tab function to work like it did a long time ago, to cycle through your latest tabs no matter what group it was in, but I'm not sure if that is going to happen any time soon.

**Comment by mzguy** [comment]
@SpaceClicker 

> I would really like the ctrl-tab function to work like it did a long time ago, to cycle through your latest tabs no matter what group it was in, but I'm not sure if that is going to happen any time soon.

I agree, something like that would be nice.

**Comment by bsdf** [comment]
same behavior observed for "Load first group" and "Load next group" on Linux. these were working flawlessly until an extension update today

**Comment by ajchow66** [comment]
Adding to this, no shortcuts set in Firefox's "Manage Extension Shortcuts" menu works except for "Open popup." Setting shortcuts in the extension's Hotkey settings page works, but as noted in the menu, it only works on webpages and not browser pages. 

I have reverted to STG version 4.8.1, which does not have this issue.

    OS and version: Windows 10 Pro 22H2 19045.2846
    Firefox version: 112.0
    Simple Tab Groups version: 5.0.1

**Comment by mzguy** [comment]
Update: on version 5.1 it's working better, but still not completely.

It seems that the next / previous shortcuts now work under many circumstances, however I've noticed that after getting to the oldest group in history (repeatedly clicking the "previous" shortcut), clicking the "next" shortcut stops working. It gets stuck on the oldest viewed group.

**Comment by Drive4ik** [comment]
Fixed. Please, wait next release (5.2)

**Comment by Drive4ik** [comment]
Does it work better?

**Comment by cachedout** [comment]
I experience this on my machine, and I'm fairly sure that the root cause is that you must completely release and re-press the shortcut key combination for the shortcut to fire.

For example, if you have a shortcut as I do which is `cmd-enter`, you cannot hold down the `cmd` key and then repeatedly press `enter`. You must instead release both the `cmd` key and the `enter` key before again depressing `cmd` again and then while holding it down, re-press `enter`. You must do this every time you want the shortcut to jump to a new group.

@Drive4ik I believe this bug should be reopened as this is definitely not fixed, even in 5.2. Thanks.
