### ISSUE TITLE
Firefox no icon to reload group 

### ISSUE THREAD

**Issue by marcelzx** [Drive4ik/simple-tab-groups#1036]
Just installed it
saved my tab to groups i created on the fly
no way to load and see them
cannot work anymore, no tabs
where is the user manual?
where is the help / support?

**Comment by Drive4ik** [comment]
@marcelzx We need more information. What browser, version, maybe a screenshot. Is it the same with other addons?

**Comment by marcelzx** [comment]
closed? Depending on which time zone you are... 
what web browser? I think I mentioned FireFox in that  header/subject of that issue. Version? the latest, 112.0.2, this browser is always up-to-date . My others add-on are ok. 
![ttt](https://user-images.githubusercontent.com/131582705/235311214-2646733f-8d36-40b8-8315-d6239c406b5a.JPG)

**Comment by marcelzx** [comment]
hello

**Comment by marcelzx** [comment]
closed? Depending on which time zone you are...
what web browser? I think I mentioned FireFox in that header/subject of that issue. Version? the latest, 112.0.2, this browser is always up-to-date . My others add-on are ok.

![ttt](https://user-images.githubusercontent.com/131582705/235984191-6ee5d7e8-22f3-4120-b08d-c16b2060340a.JPG)

**Comment by achernyakevich-sc** [comment]
> My others add-on are ok.

@marcelzx I have some ideas about your problem...

1. Since some version of Firefox by default toolbar buttons of Firefox could be not pinned to toolbar but available through Extensions toolbar button. So you probably could find your missed button there. If so then you could click gear icon and ping button to toolbar.
2. As well Firefox provides possibility to customize toolbar (other browser have no this great feature). Click to toolbar and click `Customize Toolbar...` menu item. As soon as customization mode activated you could remove or add buttons (including Add-Ons related) from/to toolbar. Probably accidentally you removed it so you can add it back. As well you could place Add-On button not only to toolbar. In my case (see screenshot below)  moved it to tabs bar. :)

![image](https://user-images.githubusercontent.com/24388336/236148716-3ff83bac-3e55-4900-aba5-136643ebd02d.png)

I hope it will help you.

**Comment by marcelzx** [comment]
1. i have no extension toolbar
2. i never customized my toolbar. The last add-on i installed is Simple Tab Groups
3. as you can see in the screenshot, i don't seem to have access to STG icon
![1](https://user-images.githubusercontent.com/131582705/236235158-882907b0-349f-4af6-9fcd-47aa128a1d7c.JPG)

**Comment by achernyakevich-sc** [comment]
> i have no extension toolbar

![image](https://user-images.githubusercontent.com/24388336/236248394-5b2e5fb9-20ef-436a-a797-7defdad55dff.png)

Click the Extensions to see other Add-Ons buttons that at the moment are not pinned to toolbar.

**Comment by marcelzx** [comment]
i found the solution. It was as simple as to pin it to the toolbar.

according to me it is a bug that when you installed this extension it does not do like the other extensions I installed and add its button

thanks for your help
