### ISSUE TITLE
Save the zoom level for each Tab to "survive" a browser restart

### ISSUE THREAD

**Issue by umbertones** [Drive4ik/simple-tab-groups#1049]
When I restart Firefox all Tabs are reset to 120% (my default). But I have one forum with 5 or so tabs that is better readable with 133%.

I'd like simple-tab-groups to memorize the tabs AND the zoom factor and restore that after a restart.

Thanks and regards

**Comment by achernyakevich-sc** [comment]
As far as I know Firefox itself remember what zoom level used per every site/domain. But it means that if you change zoom level at any tab for the particular site then all tabs will be automatically re-scaled according to new settings.

Issue looks like not related to STG itself and could be closed by author.

**Comment by umbertones** [comment]
Well,  my Firefox on Linux doesn't. 
After every restart the pages of the particular forum which are best in 133% come up with the system standard 120%.
That's why I did file it under "feature request", it's not an issue of STG.

**Comment by vitusson** [comment]
Well, my Firefox on Linux does it. For years now.

What's your "browser.zoom.siteSpecific" setting? The default is "true"
http://kb.mozillazine.org/Browser.zoom.siteSpecific

Like others said, this has nothing to do with STG at all

**Comment by umbertones** [comment]
"Nothing at al"l? What's your problem?
You make bringing up a *feature request* to save and restore the zoom level of a tab for a tool that saves and restores tabs sound like an offence.
The setting you mentioned is set to true and yes, it worked in the past. But it doesn't anymore.

**Comment by Drive4ik** [comment]
@umbertones You asked for functionality that is not part of the basic STG functionality. You're better off with any of these plugins, your choice:
https://addons.mozilla.org/firefox/search/?q=zoom

The idea of addons is that each addon does its part of the job, and what the user needs. If he doesn't need any more functionality, he deletes the addon. And making an addon a mega combine that can do everything in the world is not a good idea.

Here's another thing, if the tabs that do not save zoom had containers, STG will recreate these tabs. This is a bug in Firefox, should be fixed in version 113.

**Comment by umbertones** [comment]
Thanks for the discussion. I'll focus on regaining the zoom function of firefox.
