### ISSUE TITLE
How to prevent opening two tabs when opening bookmarks?

### ISSUE THREAD

**Issue by filipevilaca** [Drive4ik/simple-tab-groups#1076]
Hi,

When I open a bookmark in a new tab, it opens two tabs: one in the default container and one in the group’s container. This is annoying and wasteful.

I want to open the bookmark only in the group’s container, without having to choose it every time or close the extra tab. Is there a way to do that?

I looked at the extension’s settings and I couldn’t find such an option. Maybe I missed something? If there is a way to fix this issue, can someone please tell me how to do it?

If not, then I think this would be a useful feature to add. 

What do you think? Do you have the same problem or need? Do you know any workaround or solution?

Thanks for your help and feedback.

**Comment by achernyakevich-sc** [comment]
@filipevilaca I'm not sure that your issue is related to Simple Tab Groups add-on. It is more likely related to Multi-Account Containers add-on. You need to check settings of it. Probably ticking `Replace tab instead of creating a new one` could help you:
![image](https://github.com/Drive4ik/simple-tab-groups/assets/24388336/0c1fbf4b-ad0b-45c7-9da6-586dbe104092)

If it will help, could you comment here about results and close the issue.

**Comment by filipevilaca** [comment]
Yes, that fixed it. Thanks!
