### ISSUE TITLE
TypeError: group.tabs[activeTabIndex] is undefined

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#139]
I get this error if I select "Manage Groups" tab via the tabs sidebar, followed by clicking Manage Groups tab in the "Grid Display". This is the experimental version.

![2018-04-05_13-18-15](https://user-images.githubusercontent.com/5490615/38389648-9a1537a6-390e-11e8-9a67-ad7b594dfe82.png)

**Comment by SebastianSimon** [comment]
I can confirm this bug.

The group manager tab doesn’t appear to be in the `group.tabs` array. It attempts to select the index _after_ the group manager tab. So selecting this tab with another tab opened after it wouldn’t result in an error, but the other tab would just get selected.

When you select a different tab in the same group, then just go back to the group manager tab, then the group manager tab itself doesn’t get displayed anymore within the group manager. However, it seems to reappear when the group is updated.

So, could this be fixed by simply consistently never show this manager tab in the manager itself?

**Comment by Keith94** [comment]
Now the "Manage groups" page launches in its own separate window, so this bug may be considered as fixed.
