### ISSUE TITLE
Multiple Browser Window - Tab Management

### ISSUE THREAD

**Issue by taqimonster** [Drive4ik/simple-tab-groups#184]
having multiple browser instances open, tab group management is quite confusing.
Suggestion: each new window that you open for a browser, could have it's own tab groups. basically, instead of tab groups being a global setting, it would be helpful if the setting was local to each window you open.
this would massively improve functionality on multiple desktop scenarios where you have an instance of firefox open on different screens.
hopefully this is a realistic expectation.

**Comment by Drive4ik** [comment]
Please, update FF to v61 and after that update addon to v3.0 (not experimental)

But what you want will not be done due to the fact that you can accidentally close the window and at the same time all the groups that were in it will also be lost. In some cases, the restoration of a closed window can not help
