### ISSUE TITLE
all tabs loading in same group

### ISSUE THREAD

**Issue by samboa86** [Drive4ik/simple-tab-groups#200]
This new one is giving me issues when I try to switch groups, it just loads the new tabs WITH the current tabs and then that group increases in size because all tabs are open. 
So group1 had 6 tabs, group2 had 10, I am in group1 and try to open group2, it now has 16 tabs in group2.

**Comment by Drive4ik** [comment]
Hi! This is strange behavior and this should not be.
What version Firefox and STG you are using? Can you repeat this every time or did it happen once and do not happen again?

**Comment by LiCybora** [comment]
I can reproduce it with the following bad practice, but it should be considered as improper usage:

1. In `about:preferences#general`, uncheck `Restore previous sessions`.
![image](https://user-images.githubusercontent.com/40160522/42612724-75e621ac-85cf-11e8-99a0-3078b69d3902.png)

2. Open some tabs and groups.
  2.5. Remember which group you are in (for example: group1 with 6 tabs), and Quit Firefox.

3. Start Firefox again, and manually choose `Restore previous sessions`.
![image](https://user-images.githubusercontent.com/40160522/42612674-3900ac94-85cf-11e8-9a19-ca0816f6120e.png)
    - You should see the icon keep this (without triangle)
![image](https://user-images.githubusercontent.com/40160522/42614388-4d3da8ac-85d8-11e8-8825-40f19fde1920.png)

4. Select any groups other than the one before you quit (e.g.: group2 with 10 tabs), then you get 16 tabs in group2 now.  

Workaround: Reload the addon between step 3 and 4 can solve the problem (the colored triangle will be backed), or try reload it whenever you don't see the colored triangle.

I guess the problem happens when sessions restore after STG ready, regardless what reasons cause it (maybe include caused by other addons?). Because STG is currently not in any groups (you may see the colored triangle disappear in addon icon), so it will append all (unhidden) tabs of your current session into the group you are going to switch. That means: if session restore after STG ready, you are NOT really in group1, but just with all opened tabs in group1 (and hidden tabs in other groups goes `Found hidden unsynchronized tabs`). That's why group2 will also load the tabs in group1 when switching to group2.

**Comment by Drive4ik** [comment]
In general it was a feature, but I see that it only hinders a lot, so I removed it. Now if you open a group in a non-synced window, all the tabs of this window will be hidden and appear in the list "Found hidden unsynchronized tabs"

**Comment by samboa86** [comment]
Most of what you wrote was gibberish for a non dev like me.
This is what I do that produces the error:

I am starting fresh I havent used FF since the old days. So I have a back uped copy of my old tabs from old addon. So I do "Restore Quicksaver's "Tab Groups"
Load a backup file from the old "Tab Groups" addon."
I do that. the tabs look correct in the bar, and on the manage page.
But when I actually click a group, it loads them, but then going to another group, it just adds those tabs to the current group and it never lets me go to that group. then clicking another group also adds those tabs to the current group.

I also have the new hidetabs preference on, not sure if I am supposed to or not since you are doing hide tabs now.

**Comment by samboa86** [comment]
I have reproduced the error just now before writing that too, newest version of FF and addon

**Comment by samboa86** [comment]
hehe I actually just came here to say something similar before I saw your message, I created a new group, let it load the tabs in there, close the new group and now I think things are working fine. 
A few times I got an "error 33" or something, couldnt find tab ID:33 (but it always was same error) but that may be another problem for another day if I come across it again. Reloading extention a few times seems to fix.
thanks!
