### ISSUE TITLE
Changing to Next/Prev tab by using "Shortkey" sometimes switches to other tab group

### ISSUE THREAD

**Issue by yennor** [Drive4ik/simple-tab-groups#204]
**Describe the bug**

When cycling through the tabs of a group by using ctrl-tab ctrl-shift-tab that works perfectly. You can change from the last tab of a group to the first one and vice versa.
When using the plugin "shortkeys" and assigning shortcuts to the previous/next tab (I use F1 and F2 for that) then when switching from the last tab to the next it will change tab group, also when switching from the first tab to the previous tab. Sometimes it also changes tab group in the middle of a group.
I'm not sure if that would be a bug of "simple tab groups" or "shortkeys".
Maybe "simple tab groups" catches the ctrl-tab event and looks for correct cycling or something?
I've also filled a bug for the other plugin:
https://github.com/mikecrittenden/shortkeys/issues/197

**To Reproduce**
1. Install shortkeys add-on
2. assign a key to "next tab" command
3. have several tab groups
4. cycle through a tab group by u sing the above assigned shortcut.

**Expected behavior**
cycle the tabs only i nside of the tag group. don't jump to another tab group.

 - OS: Linux
 - Version 3.0.8
- firefox version 61

**Comment by Drive4ik** [comment]
Hi! This is because the "Shortkey" extension shows the next tab, regardless of the hidden tab option.
And my addon switches to the group if at least one of the tabs of this group is displayed.
You can see it on this screenshots:
![screenshot_6](https://user-images.githubusercontent.com/7843031/42453880-b9dcef98-8396-11e8-888f-f655adaf5226.png)

![screenshot_5](https://user-images.githubusercontent.com/7843031/42453892-c36d325c-8396-11e8-8975-372c45415b8c.png)

and when you were on Group 1 and enter "youtube" in adress bar, select tab and press Enter (on prev screenshot) youtube tab will change position from `hidden: true` to `hidden: false` and Group 11 (which has this tab) will load
I did this for the convenience of quickly searching for tabs using standard Firefox tools, and I will not change this behavior.
I suggest that the developer "Shortkey" add another option to account for the visibility of the tab.
