### ISSUE TITLE
Default icon non visible in dark mode with 3.0.10

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#214]
**Describe the bug**
The default icon is not visible in dark mode (see screenshots below), unless hovering.

**To Reproduce**
update to version 3.0.10

**Expected behavior**
icon should be visible without hovering

**Screenshots**
https://i.imgur.com/UIG3KGo.png
https://i.imgur.com/dMDzVzy.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.10
-  FF 62b9

**Additional context**

**Comment by LiCybora** [comment]
Set `svg.context-properties.content.enabled` to `true` in `about:config`. See #213

**Comment by klint** [comment]
In additio (but do I understand correctly that it is on purpose?), all group icons have turned to black, while I was using a color code to tell them apart
https://i.imgur.com/KFAwGAN.png

**Comment by LiCybora** [comment]
If you use old Tab Groups icon, then your color code no longer work as that icon now follow only theme color.

**Comment by klint** [comment]
Do you mean the one in red below?
But what was wrong with that one? :)

![image](https://user-images.githubusercontent.com/218971/42951312-35c4eeb2-8b76-11e8-8bd4-5e4c6ce4b346.png)

Couldn't there be 2 versions of it: one with the colour theme, one fully with a user-defined color ?
Thanks

**Comment by LiCybora** [comment]
Yes that one. The problem seems to be the hard-coded svg icon can only fill with one color, unlike the other 3 that is draw with multiple component (so one square/triangle get color and remains get theme).

By the way, extension cannot modify `about:config` page. No idea why Mozilla don't enable it by default.

@Drive4ik: Would it be possible to re-design the old Tab Groups icon and make one block with user color? Seems the new design cause confusion when using the popup with all icons identical.

**Comment by klint** [comment]
Got it, thanks for the explanation. 
And yes, please, having the old Tab Group icon with one color would be better. As an alternate version to the themed one, which may be oool for other users.

**Comment by Drive4ik** [comment]
Ok guys! You persuaded me! I redrawn this icon :)
![screenshot_4](https://user-images.githubusercontent.com/7843031/42956698-57975120-8b89-11e8-9844-2a4fd49120e1.png)
![screenshot_5](https://user-images.githubusercontent.com/7843031/42956704-5aa64c36-8b89-11e8-92fa-503b9084a775.png)
