### ISSUE TITLE
Grouping doesn't apply to file: and about: URLs

### ISSUE THREAD

**Issue by vrurg** [Drive4ik/simple-tab-groups#22]
I guess that when extension enumerates tabs it simply ignores those where URL is not of http: or https: protocols. Is it fixable? To my view, at least file: and about: could no doubt be safely reloaded after group switching.

**Comment by Drive4ik** [comment]
Hi @vrurg 

Please see "url" param in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create#Parameters

> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
> - chrome: URLs
> - javascript: URLs
> - data: URLs
> - file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
> - privileged about: URLs (for example, about:config, about:addons, about:debugging). Non-privileged URLs (e.g., about:blank) are allowed.
> - The New Tab page (about:newtab) can be opened if no value for URL is provided.


Sorry, but this is nor real((

**Comment by vrurg** [comment]
This makes it impossible for me to migrate back from Chrome. Damn it... Gonna see if containers work for the purpose.

Thanks for the answer, anyway!

**Comment by grahamperrin** [comment]
Mozilla bug [1269456 - Add permission to allow extensions to load semi-privileged URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1269456)

**Comment by frgomes** [comment]
Posting on a closed issue may be unneffective... anyway...

I usually work offline on the train or metro, for example. No internet connection.
For this reason, I have a bunch of documentation downloaded into my laptop using httrack.

However, Simple TabGroups cannot open these documents because they are all file:// protocol.

I see why Simple TabGroups does not support that. That's because Firefox restricts abilities of Simple TabGroups. However, from the user's perspective, this restriction defeats the purpose of Simple TabGroups in this scenario in particular.

Can anyone suggest a way to circumvent this restriction?
I've just imagined (whilst writting these lines!) that I could have a local NGINX (accessible via http://localhost/), configured to serve all my local content. Would that be an alternative?

**Comment by Drive4ik** [comment]
@frgomes Hi! That's right, STG cannot create a tab with the URL `file:///...` but, it can manage them.
What version of STG are you using?

**Comment by frgomes** [comment]
@Drive4ik  It's version 4.0.0.2.

Yes, apparently the "problem" is related to the abiity to "Open Bookmark in TabGroup" which fails.
I suppose that the same function is called when the browser restarts and/or when I open a certain TabGroup which contain such sort of URLs. 

I don't really expect that TabGroup can solve that since, apparently, it is a security feature imposed by Firefox. However, I would like to consider alternatives. The idea of installing nginx and configuring it to serve my local content souds like overkill.

**Comment by Drive4ik** [comment]
Yes, you cannot bookmark with a url `file://` in a group, but if you just open it in a tab, as usual, then there should be no problems with group switch. Switching between groups with such tabs goes fine.
