### ISSUE TITLE
Export to bookmarks/HTML page

### ISSUE THREAD

**Issue by vlatkoB** [Drive4ik/simple-tab-groups#224]
Currently there is no way (that I'm aware of) of exporting groups to a format that can be easily read by Firefox. That means taht if something goes wrong, we do not have a backup of groups and tabs in some standard format.

In Backup page a new option can be added for exporting to standard FF bookmarks.json file, so groups and their tabs can be easily imported to FF bookmarks menu. 
Or maybe an option "Save all Groups to Bookmarks menu".

An option to read groups from FF bookmarks.json would also be a nice addition. It would be much easier to switch to/test STG.

**Comment by as3mbus** [comment]
I would like to be able to save 1 or more unused group into a bookmark folder, but it seems like there are no way to do so (or maybe i'm missing something) but it would be great if i could just open a bookmark folder into a group and vice versa.

**Comment by Drive4ik** [comment]
Hi! I added new options - export group to bookmarks and import bookmark folder to new group. Update STG to v3.3.8

**Comment by cyberpunkbln** [comment]
Hello,
thx wooow this is very cooool. Thx.
It is possible that i can choose the Main-Folder where the tab-groups will be grouped? I mean an option for an simple "stg" mainfolder will be fully okay.
But for now its soo cool,
thx

**Comment by Drive4ik** [comment]
@cyberpunkbln You can enable the option "Export groups to main bookmark folder" in the settings and then all the groups of tabs will be saved in the folder "STG bookmarks", and you will change the location of the folder "STG bookmarks". But you cannot change the name of this folder, since a new one with the same name will be created.

**Comment by klint** [comment]
@Drive4ik 
How does this work exactly?  I'm asking because in French, the "STG bookmarks" string is translated into "Marque-pages STG", yet all groups are exported directly in the default bookmark location (in the personal bar in my case), not within a "STG bookmarks" or "Marque-pages STG" folder.

Also, the 2 related strings in the addon options are named:
"Export groups to main bookmark folder" and "Default bookmark folder location".
But "main" and "default" bookmark folders are the same, aren't they? so shouldnt' they be rather named either both "default" or both "main" for better consistency? :)
Thanks!

**Comment by Drive4ik** [comment]
@klint Hi)
"Export groups to main bookmark folder" and "Default bookmark folder location" this is a different functionality.
I agree that it was not quite convenient, I think it would be clearer))
I changed the translation title from `Export groups to main bookmark folder` to `Export groups to '$bookmarkfolder$' bookmark folder`. `$bookmarkfolder$` is taken from the `mainBookmarkFolderTitle` translation key. 
8f13991

**Comment by klint** [comment]
@Drive4ik Excellent, thanks!
Now I think I get it: when the "Export to..." box is checked, the target is the  default bookmark folder itself, and when it is unchecked, the target is the default bookmark folder location (one level above). 
But in both cases, the "Export to.." option in the group contextual menu will appear. 
Is that it?

**Comment by Drive4ik** [comment]
@klint Yes that's right ))
