### ISSUE TITLE
Refresh tabs at startup

### ISSUE THREAD

**Issue by stukdev** [Drive4ik/simple-tab-groups#255]
At startup the tabs are loaded from cache, and i've to hit manually F5 for all tabs for refresh the page.
Is there a way to implement auto refresh all tabs in the group at startup?

**Comment by Drive4ik** [comment]
Only this way:
![screenshot_2](https://user-images.githubusercontent.com/7843031/46439052-2ff65880-c768-11e8-8ff7-6fbf87ccf878.png)

**Comment by stukdev** [comment]
Why not using browser.tabs.reload API ?

**Comment by Drive4ik** [comment]
Because this functionality already exists and works and I do not want to duplicate it.

Please read this:
https://support.mozilla.org/en-US/questions/1185154

You have to set `browser.sessionstore.restore_on_demand` to `false`, restart browser and retest.

There was also a "mirror" problem from yours #223

**Comment by Drive4ik** [comment]
Or you can try this extension
https://addons.mozilla.org/firefox/addon/reload-all-tabs/

**Comment by stukdev** [comment]
I don't know the browser.sessionstore.restore_on_demand, for the moment this solve the problem!
Thanks
