### ISSUE TITLE
Every windows have its own groups 

### ISSUE THREAD

**Issue by ahmed-tea** [Drive4ik/simple-tab-groups#26]
All groups appear in all windows
Is there a possibility to make each window have its own groups?

**Comment by Zeioth** [comment]
That feature makes no sense. Just use the search bar.

**Comment by Philip-Sutton** [comment]
ahmed-tea  - seems to me that you are asking for a 'nesting' process for groups?  Maybe the list of groups that drops down from the window toolbar could display in a nested tree?  If the current window is showing a tab group that is lower in the hierarchy then the toolbar drop down list could open with the tree expanded at the level of the open tab group.  This could then show any sibling groups.
An arrangement like this allows the user attention to be directed to the sibling groups but still allows navigation to any other group.

**Comment by Drive4ik** [comment]
@ahmed-tea 
Please update addon to latest version and open addon options page. There you needed options:
"Individual window for each group"
"Open new window when create new group"

**Comment by ahmed-tea** [comment]
@Drive4ik 
What i mean
When i creat groups in a window, this groups will be belong to this window only so when i open new window, no groups shown
Example
Window 1
                 Group1
                 Group2
Window 2
                Group1
                Group2
                Group3 
Group1 & Group2 in Window 1 is not the same as Group1 & Group2 in Window 2

**Comment by Drive4ik** [comment]
I understand. Sorry, but now I can not do this opportunity.

**Comment by ahmed-tea** [comment]
@Drive4ik 
I wish you can do that in the future
This feature let the user to classified the each firefox window to a subject and each group belong to that window to sub subject

**Comment by lightfire-nyan** [comment]
+1 for this feature, the main reason being:
It will allow easier navigation across groups, especially when using the prev/next group hotkeys; i.e. each window can then cycle few just a few groups rather than all.
This was the behaviour used in the old Tab Groups extension and Panorama.
As an alternative, you could add a "hide group" option for each window.

**Comment by lightfire-nyan** [comment]
+1 for this feature, the main reason being:
It will allow easier navigation across groups, especially when using the prev/next group hotkeys; i.e. each window can then cycle few just a few groups rather than all.
This was the behaviour used in the old Tab Groups extension and Panorama.
As an alternative, you could add a "hide group" option for each window.
