### ISSUE TITLE
Tabs created before the STG is fully loaded are hidden during Firefox startup

### ISSUE THREAD

**Issue by alefpereira** [Drive4ik/simple-tab-groups#274]
There is a small interval of time right after opening Firefox and STG is loaded where you can browse tabs, create new tabs, close old tabs, etc. If tabs are created before STG is loaded, STG hide the created tabs during its sync.

Since it is not possible to switch the group while STG is loading, It would be good to include the new tabs to the loaded group instead of hiding them, and also not to change the active tab so user can continue to browse the actual tab without have to open STG menu and manually include the hidden tabs to the group.

This is extended to closed and moved tabs. STG reopen the closed tabs and sort the tabs during its sync, it also change the active tab after reopening the closed tabs. 

My Firefox is set to open tabs from previous session. Don't know the influence of this setting in STG sync.

**Comment by Drive4ik** [comment]
All this behavior is done in order to restore the tabs in the group that were before Firefox closed. This eliminates many problems. But due to the limitations of webextensions, it is impossible to do this instantly (when launching the browser, there is no access to the url tabs that load, so waiting for all tabs to load). Therefore, I chose the most painless way - thereby getting rid of various problems in the work of Firefox.

**Comment by EiniStein** [comment]
+1 to finding a more convenient solution to this.

**Comment by Drive4ik** [comment]
Please retest this issue on latest STG version

**Comment by EiniStein** [comment]
Not solved, but may be better.

**Comment by e-motiv** [comment]
+1
I really hate ths! Sometimes it takes STG several minutes to load and then you're surfing and opening tabs and suddenly all your work and tabs are gone... How I hate this! It's super frustrating...Even if some tabs are the same as before, the content is completely gone and everything has to reload....
The developer is probably doing their best, but, man, how this tests my patience..
