### ISSUE TITLE
stg-backup json files appear on recently opened files list in Gedit.

### ISSUE THREAD

**Issue by Tyrewt** [Drive4ik/simple-tab-groups#280]
Auto backup is enabled, daily. I've noticed when I open Gedit text editor, the stg-backup json file names are showing up as a recently open. Though not necessarily a problem, it does interfere with the use of this feature by pushing legitimately opened files off the list. Can anything be done to prevent this?

STG 3.3.2
Firefox 63.0
Ubuntu 18.04

**Comment by Drive4ik** [comment]
If there is a daily backup, a copy is created and overwritten every 2 hours so that when an error occurs, the latest changes are saved. In the editor, you can add a folder to the exception, if there is such a functionality.
You can set up a backup every second day, when it will be created when the browser starts, but the chance to lose the latest changes is higher
