### ISSUE TITLE
Option to stay in the same group when closing the last tab in it

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#289]
Hi
Today, when I close the last tab in a group, the next non-empty groups opens and is displayed.
Maybe there is one, but I haven't found a way to change that dangerous behaviour (if you have one group for work and one group for private activities on the work place... you may not want these tabs to appear magically when closing the last work tab ;) )
Could there be an option in the settings to allow staying in the same empty group after closing the last tab in it?
Thanks for considering this.
Cheers

**Comment by Drive4ik** [comment]
Hi! Unfortunately, the Webextensions API does not give direct control over user actions, so when you close the last tab, the Firefox window cannot be open without tabs, but since you closed the last tab, the browser looks for hidden tabs, and when it finds one, it shows it, and here it works out my plugin and switches to the group in which this tab is located.
You can make any pinned tab and this behavior will no longer be

**Comment by klint** [comment]
Hi . Thanks for the explanation. In other words, there is no way for your addon to catch and detect the closure of the last visible tab in the group and quickly open a empty tab, thus avoiding an hidden tab to be risen from the dead? :)

**Comment by klint** [comment]
One last thing if you don't mind :)
If the above is not feasible, we could leverage the "Manage Groups" view to solve the problem: actually, I now plan to leave the "Manage Group" view always open in a pinned tab. So maybe a hint about this in the option could help, don't you think?  At least a hint, but of course, an option to do that automatically could help as well.
Thanks

**Comment by Drive4ik** [comment]
Yes, making Manage groups like pinned tab is a good idea and will solve the problem if you like it that way)))
