### ISSUE TITLE
tab groups menu doesn't shows on right-button menu in tree style tab addon

### ISSUE THREAD

**Issue by kostousov-ds** [Drive4ik/simple-tab-groups#299]
**right-button menu on classic tab panel**
![firefox-tab-menu-1](https://user-images.githubusercontent.com/1400399/49850063-04de5400-fdfe-11e8-8602-4fc6173fc101.png)

**right-button menu on tree style tab**
![_2018-12-12_11-03-01](https://user-images.githubusercontent.com/1400399/49850064-0576ea80-fdfe-11e8-825f-250c72845f13.png)

**Comment by FunkMonkey** [comment]
I think this should be possible since Firefox 64 again (before you couldn't do that because Treestyle Tab basically had a custom context menu since WebExtensions came out):
- https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-10-14_override-context-on-fx64.htm#topic2018-10-14_override-context-on-fx64
- https://blog.mozilla.org/addons/2018/11/08/extensions-in-firefox-64/

**Comment by Drive4ik** [comment]
Thanks @FunkMonkey !

@kostousov-ds 
This functional was implemented in Firefox 64
