### ISSUE TITLE
STG won't load if page from last session unable to load when browser startup

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#334]
**Describe the bug**
STG fails to load if the page from last session not finished loading. This is horrible if a site is good previously but suddenly down, when you recover from last session, you take forever to load STG unless you manually abort the loading.

**To Reproduce**
1. Make sure recover from last session is on.
2. Reduce your bandwidth to ridiculously low such that it take long enough to load on every pages, or just go to `http://mgprddev2012.dream-valenciennes.com` (an example page that takes very long to load)
3. Keep on that page and close Firefox
4. Restart Firefox
5. STG never load until the page finish loading. In other words, if page take forever to load, then so as STG.

**Expected behavior**
Page loading should not affect STG loading, at least should not blocking STG when the page is partially rendered (which means the site gives response already)

**Actual behavior**
STG never finish loading if page not finished loading unless you abort it,

**Desktop:**
 - OS and version: Debian 9.7
 - Firefox version: 65 release/66 beta/67 Nightly
 - Simple Tab Groups version: 3.3.7.1

**Additional context**
Current workaround: Press stop button. However, if the browser not even receive a response from that site, then the URL of that page will be gone.

**Comment by Drive4ik** [comment]
The fact is that the addon does not have access to the url of the tab when it is loaded, and I synchronize exactly by url and not by tab ID or something else. That is, at the time of loading the tab, I do not have a url and I do not know which group the tab is assigned to. It is impossible to automatically assign a tab to the current window group since we do not know what state and with which tabs the addon is loaded.

**Comment by Drive4ik** [comment]
Please retest this issue on latest STG version

**Comment by LiCybora** [comment]
Thanks! It is nice now.
