### ISSUE TITLE
Make "Access your data for all websites" permission optional

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#364]
**Is your feature request related to a problem? Please describe.**
It is frightening that this extremely useful extension can steal all my data (passwords etc), e.g. when hacked. And all of that just for the purpose of creating thumbnails:
```
Permissions used:
    <all_urls>(Access your data for all websites): for tab thumbnails
```

**Describe the solution you'd like**
Please make the permission optional. You already have this approach for bookmarks access. When the user enables `Allow access to bookmarks` in extension options, Firefox asks the user to approve this. Please make this the same case. Many people don't need thumbnails, not for the price of potential private data theft. There is already `Create thumbnails for tabs` option present. Please make it disabled by default, and ask users for an extra permission when they enable it. There can also be some hint/button on the `Manage Groups` page to advise those users who don't look into extension settings.

Thank you.

**Comment by Drive4ik** [comment]
If it were so easy....
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions#API_permissions

**Comment by kparal** [comment]
Having two versions of this extension, with and without the required permission, is probably out of question? :disappointed:

**Comment by Drive4ik** [comment]
I don’t know how I hadn’t thought of it before ...
Made optional
Option in the "Create thumbnails for tabs" settings

**Comment by kparal** [comment]
Awesome, thank you! :fireworks: :champagne: :+1:

**Comment by aGrimRepoMan** [comment]
Regarding Drive4ik's comment above:
> 
> I don’t know how I hadn’t thought of it before ...
> Made optional
> Option in the "Create thumbnails for tabs" settings

Question: I apologize if I'm missing something obvious, but I couldn't find such an option in settings of latest STG version 4.5.5 labelled "Create thumbnails for tabs".  How do I disable STG permission for "Access your data for all websites"?

**Comment by Drive4ik** [comment]
@aGrimRepoMan 
Permission "<all_urls>" need for tab thumbnails and webRequestBlocking
webRequestBlocking is used to automatically move tabs to the desired group based on URL or container.
Also used to open tabs with the desired container that the user specified in the group.
If you make it optional, half of the addon's functionality will automatically stop working, and most users do not understand at all how and what and where to enable. Some do not go into the addon settings at all, but immediately create an issue on github or put one star in the rating. What can I say ...

**Comment by aGrimRepoMan** [comment]
Understand. Thanks for the reply.

As a compromise, is it possible that the default after successful installation of STG is to have permission "Access your data for all websites" enabled (i.e, as it is today), but "power users" (those who are willing/able to explore the STG extension's settings) can disable tab thumbnails and automatic tab movement functionality, triggering removal of "access your data for all websites" permission?

**Comment by Drive4ik** [comment]
@aGrimRepoMan 
As soon as I make this permission optional, it will be automatically disabled for both current users and new ones. This is the point, since it is optional, it means it is turned off and those who need it will turn it on. Therefore it is not possible ..
And you needlessly worry about this parameter. This does not mean that the addon collects your personal data and sends it somewhere, for this you need access to the site to which the data will be sent. There are many addons that ask for access to certain sites, for example online translators, which for example ask for access to translate.google.com. For this, there was a complete refactoring of FF under webextensions. So that the user himself controls the permissions and where the addon has access.
In fact, any extension that has tab access has access to the URL of the tabs you are using. But only to send data somewhere - you need access to the site where the sending will be made.
STG does not collect personal data, passwords (no addon has access) and does not send them anywhere. Except for the actions of the user himself - access to bookmarks or a backup expert to a file. Also, an addon can be done with other addons from its white list with the group name, group icon, state (the group is loaded or not), etc. Several options except tabs:
https://github.com/Drive4ik/simple-tab-groups/blob/b57aecaa11f7381a461b0387cd7cbfed5766d620/addon/src/js/groups.js#L407-L417

**Comment by ogrisel** [comment]
I would be interested in lightweight STG variant without thumbnails and automatic tab movement functionality that would not require the access data permission. I just don't want to run the risk that an automatically updated future version of this extension starts to silently collect sensitive personal data.
