### ISSUE TITLE
How to get rid of hidden tabs?

### ISSUE THREAD

**Issue by ddTech** [Drive4ik/simple-tab-groups#373]
This tool is fabulous! I was missing tab groups so much. I had so many open tabs, that FF was using up a good amount of my RAM. 
I moved 165 tabs to groups and now RAM usage is a lot more conservative. 

However, every time I switch from one group to another, the former tabs are moved to "hidden tabs" which is good if there are tabs among them not organized in groups. 
But most of these tabs now are members of one or the other group. This makes it difficult to distinguish between new (= unorganized) tabs and members of other groups. 

The list seems to be getting longer and longer and I have no idea how to properly get rid of the unnecessary ones. Closing and reopening FF recovers those as well and by manually closing them, they seem to be removed from their groups as well. 

I've set "Verwerfe Tab" nach verstecken (schont RAM)" ( "dismiss tabs after hiding (conserves RAM) " ?), but that does not seem to make a difference, at least concerning the list.

Do You have a tip for me?

thanks, 

Frank

**Comment by duttyend** [comment]
I have exactly the same question, wondering what will happen with this "Hidden Tabs" list and if it won't grow too big after months of use.

Thank you so much for this awesone extension !

**Comment by dcaravana** [comment]
Same here.

Sometimes is switching groups that causes them to go in the Hidden Tabs list, sometimes is moving a tar in another group (but not always...).

Really weird bug, difficult to spot patterns here, but also quite confusing when for instance you click on a hidden tab and it moves the current window to the tabs contained in the group that tabs actually belongs to...

That's scary.

I honestly think this bug should be fixed as soon as possible as it gives a bad impression more than being an actual threat to reliability.

**Comment by Drive4ik** [comment]
Hi all!
Guys, all you are saying was done on purpose, this is such a behavior. The fact that you will have many hidden tabs will not affect the operation of the browser, because after launching they are not loaded and are not in RAM. In extreme cases, you have the opportunity to manually unload a tab / group from memory using the context menu. And the fact that you manually show the hidden tab from the Firefox tab menu is not the right approach. The fact that it loads the group in which there is such a logic for when you write the name of this tab in the url bar and click on it, then you switch to the group where it is located, since the tab there is not just like that - the user put it there, and moving a tab without its consent is wrong.

**Comment by ddTech** [comment]
Thanks for the response. 

Keep up the good work.

regards

Frank
