### ISSUE TITLE
Want to be able to switch back to the normal firefox tabs (outside of any groups)

### ISSUE THREAD

**Issue by richarddwang** [Drive4ik/simple-tab-groups#389]
After I switched to one group, I done something, and I want to do something not related to any of my groups, because I don't want to mess up my groups, I need to open a new browser window to get out the scope of groups, which is not that handy.

I want to be able to click addon button, switch back to just normal firefox tabs, and
- switching to another group doesn't make normal tabs to disappear
- but turning down browser does.

Very appreciate for your work. Thanks!

**Comment by Drive4ik** [comment]
You can just turn off the addon in the addons manager.

**Comment by Shdwdrgn** [comment]
It's a shame the original request wasn't understood and they never came back to check on it.  However I now find myself in the same situation...  I have multiple firefox windows open.  Only ONE of those windows uses tab groups, all of the other windows are stand-alone and do not use any groups.

Last night I accidentally selected a group in one of the windows that does not use groups.  What a mess!  All of the tabs in that window were moved into the group without my knowledge.  All of the tabs that WERE in that group are now floating outside of any group.  This is not cool!  How do I get all of these tabs OUT of any groups like I intended them to be?

There should never be a reason why all of the tabs in a window are just automatically placed into a group without use consent.  And there should be a way to deselect all groups in the window (basically going back to view the 'other' tabs that are not assigned to any group).  It appears that the only way you can even see those tabs which are not assigned, is to assign them to a group (which I don't want).

As the original poster stated, we don't always want all of our tabs assigned to a group, nor do we want all of our windows trapped within a tab group.  In my case each window has a purpose, and usually that does not include a tab group.  This tool is very handy in the cases where I want to use it, but once you enter a tab group there appears to be no way to escape.

**Comment by Drive4ik** [comment]
@Shdwdrgn You can do the following:
In window 1, select the desired group
Open new window 2 (no group)
In window 1, select the desired tabs (Ctrl + tab click or Shift + tab click) and drag & drop tabs into window 2
this tabs will automaticaly moved from window 1 (with group) to ungrouped window without group.

In the future, I will unload the group from the window and unload the necessary tabs from the group.

**Comment by Drive4ik** [comment]
@Shdwdrgn 
As for the fact that the group assigned window tabs without a group, this is not without the user's knowledge, because you chose to load the group into this window. If the addon will check if there are tabs in the group and ask the user whether or not to load the group into the window, then this will be a very long time, and it is not always possible to ask the user.

**Comment by Shdwdrgn** [comment]
Thanks for the tip on moving the open tabs to a new (ungrouped) window.  That worked, but now I'm having an issue with the window they were in.  Every time I try to close the last tab in the window, it pulls another tab from somewhere else.  If I try to close the window, it asks me if I want to close 13 tabs (there is only a single tab actually open) and I don't know what it's going to close.  I can't even make a backup of whats currently open because the newer version of Firefox no longer has the option to manage sessions.  Just not sure what to do now to keep from losing information.

Regarding your second reply about the group being assigned to a window... I don't know what you mean about it being with the user's knowledge.  As I said, I had a window which had no groups open.  I clicked on the group manager and chose to open an existing group (because I forgot which window I was looking at).  All of the contents on the window I was in were moved into the group I selected, and all of the tabs that WERE in that group are now un-grouped (only found by looking at the 'show other tabs' option).  At no time did it ask me if I wanted to move tabs to a different group or change anything, it just all happened automatically and without warning.  If this is supposed to be a standard action then it's a bad one, because the user has no idea all of this is going to happen.

**Comment by sebu10n** [comment]
> Every time I try to close the last tab in the window, it pulls another tab from somewhere else. If I try to close the window, it asks me if I want to close 13 tabs (there is only a single tab actually open) and I don't know what it's going to close.

I had the same issue. I had 5 FF windows and wanted to use STG to still organize my tabs but have less windows open. I got it down to 3 windows after moving some of my tabs from the not-STG windows to groups. So I had 3 STG windows open and no not-STG window at all. Then I wanted to reduce them to 2 windows but I was afraid of just closing a window (also because of some bad reviews on the browser addon site).

I created a new (useless) group, switched the window to that group, closed it and hoped for the best while I clicked ok on the FF warning message that XY tabs would be closed.

It worked!

It would really help to have a button or menu entry like "Remove this tab from STG" or an STG Off switch for a single window.

**Comment by Drive4ik** [comment]
@Shdwdrgn @sebu10n 

Here's an example.

You have two windows. One main thing (first), the second is just empty you just opened.
In window 1 (main) you have Group 1 loaded
In window 2, you have nothing loaded (about:home page).

In window 2 you choose to load Group 2 which has 4 tabs.
Then in window 2 you choose to load Group 3, which has 5 tabs.

Current state: you have 9 tabs in window 2, 5 of them you see (tabs of group 3). The other 4 tabs are hidden (group 2). Therefore, when you press close window 2, FF will ask you to close 9 tabs.

In general, I put an option in this pop-up so that it no longer pops up.


>It would really help to have a button or menu entry like "Remove this tab from STG"

You must move the tab to another window that does not have a group. Only this way, it won't be otherwise.

> STG Off switch for a single window.

![изображение](https://user-images.githubusercontent.com/7843031/96177527-b092e680-0f36-11eb-9bd1-a8b8ed01d797.png)


disable this checkbox in addon options (if it was enabled)

![изображение](https://user-images.githubusercontent.com/7843031/96177441-922ceb00-0f36-11eb-814b-c9cd76ec1a25.png)

**Comment by rogergr311049** [comment]
I wonder if there is another way to reject any Group or Groups.
As far as I understand the only way is to  "**Upload the Groups**" and so Firefox will return to its initial status.
In addition, I cannot understand (and cannot force it to work) the utility:  "**Discard Group**", since it doesn't eliminate the Group as I thought...
