### ISSUE TITLE
Killed Firefox process and STG got in to a bad state

### ISSUE THREAD

**Issue by SpaceClicker** [Drive4ik/simple-tab-groups#410]
**Describe the bug**
My browser was hung up and I had to kill one of the Firefox processes (which killed all Firefox processes).  When restarting the browser, I got this message on the button for STG addon:
"Something went wrong, click here to reload STG addon"

If I click on this, it gives this error in a popup in the lower right corner:
"Error. UnknownError - The operation failed for reason unrelated to the database itself ..."

and the error on the button above persists (STG does not properly start)

I was unable to get STG to run, and if I go to the setting page it says "Waiting for all tabs to load.  Please wait..." so could not get to the restore/backup page.

I was unable to load any backups due to this.

I had to uninstall STG and then reinstall and then load the most recent backup to get it working again.

**To Reproduce**
1. Kill Firefox process
2. Restart browser

**Expected behavior**
Simple Tab Groups to load normally when processes are killed unexpectedly.  Secondary, if STG gets in to a bad state, there should at least be the option to load a previous backup instead of getting the message about "Waiting for all tabs to load".  You should not have to "wait for tabs to load" before offering the option to load a backup.

**Desktop (please complete the following information):**
 - OS and version: Win7
 - Firefox version: 67.0.4
 - Simple Tab Groups version: 3.4.4

**Comment by Drive4ik** [comment]
Do you have the same error on STG v4?

**Comment by LiCybora** [comment]
I cannot reproduce exactly the same bug as OP, but I reproduce another behavior for this bug.

STR:
1. Make sure Firefox multiprocessing is enabled (default is on as long as you dont touch it).
2. Open task manager (for Windows OS, or sth like that in other OS) and kill the process corresponds to extension (usually the second highest memory usage when no heavy page is load).
3. Firefox still operate normally, but when you click on addon popup, you get blank.
4. Kill the tab processes one by one and seeing tab crash until no more can be killed.
5. Kill the main Firefox process (Usually the one use highest memory)
6. Open Firefox again and it ask you to restore session.
7. Regardless you restore or not, all groups become empty and all tabs become `unsynchronized tabs`.

Btw, the reload button disappear since v4.0.0. I remember that button is necessary when session restore from crash in previous version.

**Comment by Drive4ik** [comment]
Guys, keep in mind that all tabs and their sessions are saved by the browser in version 4.0 and higher. If you break the browser by completing the processes, I cannot help in any way. Only restore from backup.

> Btw, the reload button disappear since v4.0.0. I remember that button is necessary when session restore from crash in previous version.

This button is no longer needed since the session is read every time you open any window to download the latest version of the current state of tabs and windows.
