### ISSUE TITLE
Bug following PC crash

### ISSUE THREAD

**Issue by skyline-ch** [Drive4ik/simple-tab-groups#411]
**Describe the bug**
After a crash of the PC I restart FireFox, your extension in load more correctly there is a yellow triangle instead of the icon.

At the bottom of the page, the preference of the plugin is "Waiting for loading all the tabs, please wait ..." if it remains even after several 10 minutes.

I uninstall and reinstall but it remains idant.

By clicking on the yellow triangle there is an error message that appears in system notifiaction (see capture)

**Screenshots**
![Capture d’écran de 2019-07-08 23-26-58](https://user-images.githubusercontent.com/13089438/60844007-70dc3b80-a1d8-11e9-8eea-7f1cc5a88231.png)

**Desktop (please complete the following information):**
 - OS and version: Ubuntu
 - Firefox version: 67.0.4 (64 bits)
 - Simple Tab Groups version: 3.4.4

is there a data file that would be stored on the PC that I could recover or repair ?

**Comment by inspector71** [comment]
I doubt this is to do with your PC crashing. I expect Firefox updated to 68 when you started it after the crash and you are seeing a different error but with the same source:

`resource://gre/modules/ExtensionUtils.jsm 0:1`

As I am seeing after simply upgrading to 68.

Since when did Mozilla decide to remove (?) this ExtensionUtils.jsm file?

**Comment by skyline-ch** [comment]
thank you for the answer
I do not understand what I have to do, I control the update there is no available.
My version is good 67.0.4

Firefox name
Version 67.0.4
Build ID 20190620092152
Mozilla / 5.0 User Agent (X11; Ubuntu; Linux x86_64; rv: 67.0) Gecko / 20100101 Firefox / 67.0
Linux operating system 4.15.0-54-generic

**Comment by skyline-ch** [comment]
I received today the update of FireFox, the problem is always present

name Firefox 
Version 68.0
Build ID 20190706110151
Mozilla / 5.0 User Agent (X11; Ubuntu; Linux x86_64; rv: 68.0) Gecko / 20100101 Firefox / 68.0
Linux operating system 4.15.0-54-generic

**Comment by S1llyG1t** [comment]
I'm having the exact same issue and it also occurred directly after a PC crash(prob due to an unstable OC I've been trying).  Using latest version of FF 68.0.1 on Win10x64.  This really sucks as there's no way to restore tabs groups, let alone even using the add-on at all to recreate groups.  Please help!

**Comment by bodo-git** [comment]
I had the same issue after a PC crash on Linux Mint 19 with firefox 68.0.1. After removing and installing the addon again, it is working. I even restored the groups from an STG backup.

**Comment by skyline-ch** [comment]
For my part I had to reset completely FF, then reconfigure everything.
I was able to recover the groups with an automatic backup that I had
it's also a pity that there is such a problem that completely break the plugin and falfs to reset all FF

**Comment by Drive4ik** [comment]
Who has the same error on v4?
