### ISSUE TITLE
PINNED TABS

### ISSUE THREAD

**Issue by EstherMoellman** [Drive4ik/simple-tab-groups#433]
Hi @Drive4ik ,

After the recent big STG' upgrades/updates, pinned tabs now are behaving different.

Normally, if one pinned tab was selected (active / focused), jumping to another STG' group never changed the pinned tab selection (the STG' group changed, but the pinned tab always remained selected).
Now with the latest STG' upgrades/updates, if I jump from one STG' group to another, the pinned tab is unselected, and instead one tab from the jumped STG' group appears selected.

I understand people may want pinned tabs as part of STG' groups. But the opposite also is valid: I don't like pinned tabs inside STG' groups. If due to STG' updates pinned tabs now are considered part of specific STG' groups, perhaps it will be a great idea to add an option allowing users like me to keep pinned tabs out of STG' groups.

Thanks!

**Comment by Drive4ik** [comment]
I thought it would be better))
Now the logic will be like this:
if the pinned tab is active, when changing a group it will remain active except if you did not explicitly specify which tab of this group to load when loading a group.

**Comment by EstherMoellman** [comment]
@Drive4ik ... as usual... I LOVE YOU!

**Comment by Narror** [comment]
Hi, is it still possible to do the opposite? 
I can't find the option

I want to pin some tab on some groups and uncheck "restore the previous session"

**Comment by Drive4ik** [comment]
@Narror If you uncheck the "restore the previous session" checkbox, the STG addon will stop working correctly and you will lose tabs in all groups - they will simply close and FF will not restore them every time you start the browser.

**Comment by Narror** [comment]
@Drive4ik 
Yes i know, I want firefox to close my tabs when I close my browser.
However, I use the notion of pinned tabs and when i'm in one group a can see pined tabs of others groups.
Example
![image](https://user-images.githubusercontent.com/26810388/98264967-27992900-1f91-11eb-8e8d-0a3976f4d24d.png)

So, I would like to have an option to hide the pinned tabs that are not part of the group I am using

**Comment by Drive4ik** [comment]
@Narror STG has no control over pinned tabs. And that is why he cannot hide them. Not only that, pinned tabs cannot be hidden at all. They must first be unpinned and only then it is possible.
If it were possible, I would have integrated pinned tab management a long time ago.

**Comment by TrustKibou** [comment]
@Drive4ik 

First, I would like to say that you are AMAZING for developing this app - I absolutely love it.

Secondly, I found this thread because I was looking for basically what Narror was asking for... but I see there's no way to create pinned tab management. So I was wondering, is there any way to make an _alternative_ specifically for STG? Basically the same thing as pinned tabs for select groups (show when group is selected, hide when a different group is chosen), but make it native to STG / not deal with Firefox's pinned tabs at all?

If that's a stupid question, I am sorry... I am new to programming and have no idea how it works with Firefox. xD Thank you again!!!!
