### ISSUE TITLE
Slight, but noticeable lag in displaying list of groups when clicking taskbar icon.

### ISSUE THREAD

**Issue by midgleyc** [Drive4ik/simple-tab-groups#440]
**Describe the bug**
Slight, but noticeable lag in displaying list of groups when clicking taskbar icon.

**To Reproduce**
1. Create at least one group (you might need many and many tabs to make it lag enough?)
2. Click on the toolbar STG item
3. Observe that the menu doesn't all load immediately -- you might get nothing, or just the "Manage groups" bar, and then the rest of the popup loads after a short delay.

**Expected behavior**
As in 3.4.4, entire popup loads instantly.

**Screenshots**
Do you know a video tool? Screenshots alone won't help.

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 68.0.1
 - Simple Tab Groups version: 4.0.0.1

**Additional context**
This is a minor problem and I reckon I could get used to it -- it's just a slightly worse experience to not be able to see all the groups immediately on clicking the button.

**Comment by Drive4ik** [comment]
Hi! This is not a bug. In version 3 and below, all tabs were stored in the add-on's memory, and loading was fast. But this has another side - a lot of bugs, and unnecessary code. In v4, tabs are stored only in browser sessions, so to display them you need to read all browser tabs and their sessions. It turns out that the more tabs - the longer the popup goes. But I did a mini cache to speed things up. While to make faster display does not work.
