### ISSUE TITLE
Grey out discarded group and indicate current tab in all groups

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#441]
**Is your feature request related to a problem? Please describe.**
The manually discard tab is a useful feature to discard group with too many opened tab. However, just opening the popup cannot tell which group has active tabs. Users still require to open group one by one, not very convenient.

Another problem is when switching to another group (without clicking certain tab), it is unknown which tab will be opened in that group.

**Describe the solution you'd like**
For first issue, group might be grey out if none of tab in that group is active. Even better if the number of active group can be shown, e.g.:
 `Foo     > 10 tabs (3 active)`
This help user to decide which group should be discarded without clicking into each group.

For second issue, highlight that tab just as current group (or any indicator should work), so that user can predict which tab will be opened when switching by hotkey without memorize their last used.

**Describe alternatives you've considered**
One of the option for 2nd issue is displaying the current tab name after the group name so that user know which tab will be opened when switching to it without opening the group. e.g.:
`Foo | GitHub > 10 tabs (3 active)`
However, this might add many text when opening the popup and some users might not like the idea, so it will be better as an option for user opt-in.

**Additional context**
Not yet

**Comment by Drive4ik** [comment]
Hi! This is an interesting idea, but there is one thing.
How to fit the words in the menu on the right? Where the tabs are.
`103 tabs (34 active)`
I don’t want to greatly enlarge this area because there will be little space for the name of the group, and there you also want to make the name of the active tab .. This all entails an increase in the width of the window, but for example in this menu it is limited and very small ..
![изображение](https://user-images.githubusercontent.com/7843031/63961116-a4c93400-ca98-11e9-9d82-d29a6a0b3e41.png)

Different languages also have different lengths of word `tabs`.
![изображение](https://user-images.githubusercontent.com/7843031/63960682-bc53ed00-ca97-11e9-85a6-b1ee11a22d3c.png)

Need to come up with some elegant solution, and not clutter up the interface, or make it customizable but not by default.

I like the idea with an active tab and the number of loaded tabs :)

**Comment by LiCybora** [comment]
How about just `3/13 active` in the column?

There is sufficient large space for name of active tab, if the addon icon is not hidden and the group name is not long. The full name of active tab is not required, 15-20 characters might good to indicate which tab will be opened.

If still not satisfactory with the extra width, how about use of tool tips like this without changing any of popup size:
![image](https://user-images.githubusercontent.com/40160522/64085592-4fc24200-cd66-11e9-8edb-736a80d55593.png)

Information will be shown when cursor on it for a while, and the desire information will be 
`<Group Name> <In-use tab name> (2/3 tabs active)`
You have already done it on tabs column for displaying full tab list. Possible enhancement can be:
```
<Group Name> (2/3 tabs active):
-> * <active and in-use tab name>
<inactive tab name>
* <active tab name>
```
`*` before the tab name to indicate active tabs, and `->` indicating which tab is opening on tab group.

**Comment by Drive4ik** [comment]
Like this (you will need to enable the option in the settings `Show active tabs in groups popup`):

![Screenshot_1](https://user-images.githubusercontent.com/7843031/65050445-10a00d80-d970-11e9-8894-d4ede0123e09.png)
