### ISSUE TITLE
Fast Group Switching causes bug in Tab Suspender

### ISSUE THREAD

**Issue by neomodern** [Drive4ik/simple-tab-groups#45]
[Tab Suspender](https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader/) I think works similarly to your 'fast group switching' feature by creating a placeholder rather than keeping a webpage loaded, except the usecase for Tab Suspender is to suspend inactive tabs in your current tab group (after e.g. 15 mins) to save RAM and boost performance.

The problem is when Tab Suspender suspends a tab, then you switch to a different group then back again, the suspended page doesn't unsuspend properly. You normally can just click on the page and it'll unsuspend, but Simple Tab Groups causes that to stop working.

**Comment by Drive4ik** [comment]
Hi @neomodern 

I investigate this behavior and I can say that I can not fix it.
"Tab Suspender" addon to restore the tab programmatically pushes history back, and does not load the saved url into the current tab.
That's why when groups change - then the tabs are created anew, and there are no history items.

You need to create a issue in "Tab Suspender" github page
https://github.com/rNeomy/tab-suspender/issues

**Comment by neomodern** [comment]
Okay I'll try that, thanks @Drive4ik
