### ISSUE TITLE
Constant "Access your hidden tabs" popups being displayed by FF

### ISSUE THREAD

**Issue by flexibeast** [Drive4ik/simple-tab-groups#460]
Context: Void Linux; Firefox Developer 70.0b2 (64-bit); STG 4.0.1.2.

This might well be an FF issue rather than an STG issue, but let's start here. :-)

i've recently started getting a FF popup whenever i move a tab from one group to another, and whenever activating a tab that's greyed-out in its STG group list. The popup says "Access your hidden tabs. An extension, [STG icon] Simple Tab Groups, is hiding some of your tabs. You can still access your tabs from [down arrow icon]."

i find this behaviour of FF annoying, but i'm not sure whether it's a bug in STG, or FF "working as intended"; there certainly doesn't seem to be any about:config option to disable this behaviour (or at least reduce it to only *one* warning per browser session).

**Comment by SebastianSimon** [comment]
I think it’s an intentional pop-up from Firefox. Just click “Keep tabs hidden”; then it won’t show anymore (at least until the next add-on update or when enabling the add-on).

Currently, I’d like to file a related issue on BugZilla. The buttons are blank for me.

![Bildschirmfoto vom 2019-09-03 15-02-35](https://user-images.githubusercontent.com/37915283/64175650-0ce29600-ce5c-11e9-9bd6-6e482cf8df34.png)

I’m wondering whether the buttons show up normally for you. I also see a “TypeError: browser is null.” at `resource://gre/actors/BrowserElementParent.jsm` in the browser console every time I switch groups (causing the pop-up to appear) and a `NS_ERROR_UNEXPECTED:` following it. Can someone confirm that these errors are directly related to the blank buttons, i.e. if you trigger the pop-up and you can read the buttons, do you not see those two errors?

**Comment by flexibeast** [comment]
Sorry, i'm not sure i follow. Where is the option "Keep tabs hidden"? It's not in the popup:

![hiddentabs](https://user-images.githubusercontent.com/190652/64180458-27daf780-cea8-11e9-9c16-805f2d50fcf0.png)

Also, i'm not sure exactly which buttons are blank for you?

**Comment by flexibeast** [comment]
Oh wait, you mean those two grey sections at the bottom of the popup are buttons without text? i pressed TAB when i last got the popup, and the grey sections suddenly included text saying "Disable extension" and "Keep tabs hidden"; i then selected "Keep tabs hidden", and yes, the popup has stopped appearing.

**Comment by SebastianSimon** [comment]
Yes, exactly! 😄 The right button should read “Keep Tabs Hidden”.
That’s very interesting. It appears that the pop-up is scrolling down as soon as one of the buttons is focused; apparently the height of the pop-up is too small.

**Comment by flexibeast** [comment]
As this was indeed an FF issue, and the [FF bug opened](https://bugzilla.mozilla.org/show_bug.cgi?id=1578611) by @SebastianSimon has now been closed resolved, i'm closing this issue.
