### ISSUE TITLE
infinite loading of the popul

### ISSUE THREAD

**Issue by ZeeD** [Drive4ik/simple-tab-groups#484]
from a pair of days, I have a problem with the plugin; clicking on the icon (or with the F8 shortcut) instead of the list of the groups, all I see is a "infinite" 2-spinning-arrows loading icon.

if I look at the extension debug console I see a lot of errors.
* merely at the mouseover on the STG icon:

```
08:35:41.154 TypeError: this.hostVsStores is undefined storage.js:276:19
```

* clicking on the STG icon:

```
08:35:41.154 TypeError: this.hostVsStores is undefined storage.js:276:19
08:35:43.984 TypeError: BG is undefined popup.js:16508:5
08:35:44.192 [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 75"  data: no] ExtensionCommon.jsm:75:12
08:35:44.195 TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:559:25
```

looking at the code, I see `const {BG} = browser.extension.getBackgroundPage();`, but https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage says it's always an object, so I don't know how could be undefined...

-- EDIT --

Is the syntax correct? I don't know well the last versions of javascript, but I've made a pair of tests:

```
08:46:14.346 const {XX} = browser.extension.getBackgroundPage(); XX
08:46:14.389 undefined
```
```
08:46:17.972 const XX = browser.extension.getBackgroundPage(); XX
08:46:18.005
Restricted moz-extension://4446f1b5-d3d4-480b-a0f0-c902e59fb852/_generated_background_page.html
```

**Comment by bloodmandarin** [comment]
I have the same problem.

**Comment by Drive4ik** [comment]
@ZeeD Hi!
I need to find out what other addons you have, since I do not have the variable `this.hostVsStores` in the code.
But apparently it affects my addon ...
Can you please enable debug mode in the add-on settings, click Start logging in popup and try to replicate the issue, and after replicate - click stop logging

**Comment by fschreiber** [comment]
Hi @Drive4ik,

it seems that I am experiencing the same issue. When I upgrade to the latest version of STG the plugin does not work. When I click on its icon I only see two spinning arrows. Also the options tab of the plugin is empty.

![stg1](https://user-images.githubusercontent.com/5478402/71259698-55558f00-2339-11ea-9804-d555907f3a99.png)

I tried disabling all other plugins but the issue persisted. Installing STG plugin on a clean Firefox install worked however.
I had not updated my STG version for quite some time and the installed version 4.0.1.2 does work without problems with all my other plugins. Only updating to the current version breaks the plugin.

In your previous reply you suggested enabling debug mode, but I cannot find where to enable it. Can you be more specific? However, I doubt that i could start logging because the popup is empty. If I can do anything to help debug the issue please let me know.

Thanks,
Frank

**Comment by Drive4ik** [comment]
Hi guys!
You can enable `debug` mode in addon settings, then open popup and if you see error message notification, in addon settings will appear button with errors:
![изображение](https://user-images.githubusercontent.com/7843031/72907993-83196380-3d3d-11ea-9868-e9ca9b77f30a.png)

**Comment by fannt** [comment]
preferences not opening as well - blank screen. nothing special in console, couple of CSS errors tho

**Comment by fschreiber** [comment]
Hi,
just for information, I started with a clean install recently and the issue did not reappear for my setup. I had not been able to start debug mode because the addon options were not accessible. 
Thanks for the effort you are putting into the addon.
