### ISSUE TITLE
Hotkey for opening popup has stopped working

### ISSUE THREAD

**Issue by slovdahl** [Drive4ik/simple-tab-groups#496]
**Describe the bug**
Opening the STG popup with a hotkey doesn't seem to work any more (i.e. the same popup that opens when the icon on the screenshot is clicked). I have had Ctrl+E as a hotkey for this since I started using STG, but it has stopped working recently, I'd say during the last 1 or 2 weeks. It doesn't seem to be possible to add a hotkey for this any more at all.

![stg](https://user-images.githubusercontent.com/1417619/68997276-519f9a00-08ad-11ea-8314-78dbce82c91a.png)

**To Reproduce**
1. Press Ctrl+E (or whatever keyboard combination it's bound to)

**Expected behavior**
The popup opens.

**Desktop (please complete the following information):**
 - OS and version: Ubuntu
 - Firefox version: 70.0.1
 - Simple Tab Groups version: 4.3.6

**Comment by slovdahl** [comment]
FWIW, I just confirmed that the same issue exists on MacOS as well.

**Comment by slovdahl** [comment]
I just found out by mistake that F8 on MacOS actually opens the popup. 🤔

**Comment by tonycpsu** [comment]
Seeing same behavior here.  v4.3.6.1, Firefox 70.0.1, OS X.

**Comment by sjsrey** [comment]
F8 works  ff 70.0.1, Ubuntu.
But custom keybindings do not.

**Comment by Drive4ik** [comment]
@sjsrey custom keybindings not working on browser secure pages, like `about:addons`, `about:preferences` etc
![изображение](https://user-images.githubusercontent.com/7843031/72894615-5dcc2b80-3d24-11ea-89f6-72dab9b98fe2.png)
![изображение](https://user-images.githubusercontent.com/7843031/72894625-67559380-3d24-11ea-9cba-b8e7269fb87e.png)

**Comment by slovdahl** [comment]
So just to make it clear: the "Open popup" shortcut shouldn't be configured in the extension settings, instead, it should be done according to the screenshots in the post above.

**Comment by Drive4ik** [comment]
Why should not be configured? This is one hotkey that opens the addon main menu. Some users do not want to configure anything, and use everything "out of the box".

**Comment by slovdahl** [comment]
Because the "Open popup" option is not available at all in the "Hotkey" extension settings.

**Comment by Drive4ik** [comment]
All is correct. Because the execution of this function must comply with the necessary conditions:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup

> You can only call this function from inside the handler for a [user action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).

user action:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions
and this is very difficult, if at all possible, to achieve without loss of functionality.

Therefore, it’s okay if the user sets up this hotkey elsewhere, but it will work fine. And the user will configure finer tuning, or one-on-one functions for different hotkeys in the add-on settings.

To be honest, what I did, or rather, setting up a hotkey in the add-on, is wrong. And it was done when there were no hotkey settings in Firefox itself.
My option does not always work and has many limitations.
Therefore, if users have more and more problems in working with hotkeys in the settings of the STG addon, maybe I will remove this functionality altogether and leave only the native support for hotkeys in the browser https://github.com/Drive4ik/simple-tab-groups/issues/496#issuecomment-577160830  ...
