### ISSUE TITLE
automatic dark theme setting

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#502]
Dark theme setting must be taken from the browser settings, rather than bother users with superfluous checkboxes.

**Comment by Drive4ik** [comment]
This is hard to do. You can get the colors of the current browser theme, but assigning them to a popup (based on the theme) will be difficult, because there are simply no colors in keys (topbar, tabs). Even in default FF themes.
Plus, you need to tell the user to include the `svg.context-properties.content.enabled` parameter in `about:config` page. To make everything look beautiful.
Also, the problem is that there aren’t some colors, which means you cannot accurately guess which color to replace the empty field with and how it will all look.

Colors for default light theme:
![изображение](https://user-images.githubusercontent.com/7843031/74236823-c3378a80-4cda-11ea-9594-e9149efa1a09.png)

Colors for default dark theme:
![изображение](https://user-images.githubusercontent.com/7843031/74236852-da767800-4cda-11ea-8441-a88a96f0e797.png)

**Comment by 532910** [comment]
It's a pity. I think it's low priority, leave it open untill it becomes clear.
I've opened the same issue for browserpass https://github.com/browserpass/browserpass-extension/issues/203

**Comment by Drive4ik** [comment]
Ok.
I have an idea, I can write a function that will define the main color of the theme, such as the color of the topbar. And if it's dark, change the addon theme to dark and vice versa. Not considering the other colors. But it seems to me that this function will have problems and bugs with the definition of color. For example, the dark yellow color in topbar. Is it a dark or a light theme?
And the problem remains to inform the user that `svg.context-properties.content.enabled` has changed its setting.

**Comment by 532910** [comment]
I've found addon that respects main theme: Tampermonkey:

![image](https://user-images.githubusercontent.com/14617699/74349459-58af4900-4dc5-11ea-8a52-9bfe0ecc76a8.png)

![image](https://user-images.githubusercontent.com/14617699/74349382-3caba780-4dc5-11ea-8ad5-b17028bbf44f.png)

**Comment by 532910** [comment]
Possible it will be better do not remove theme selection completely, but add `auto` as a default setting.
