### ISSUE TITLE
Option to hibernate groups

### ISSUE THREAD

**Issue by pintassilgo** [Drive4ik/simple-tab-groups#508]
Inspired by [Tiled Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tiled-tab-groups/) (stashing function), but I prefer Simple Tab Groups due to container rules.

Sometimes I keep some tabs opened for days as "read it later". These tabs aren't useful until I select them (what may not happen over a session) and I don't want to replace them by bookmarks. So I think we should be able to hibernate specific groups.

What I mean by hibernating group is to not be selectable via hotkeys to switch to another group, it should get skipped.

But tabs from hibernating groups should still be stated as "open tabs" just like any unloaded tab. For instance, typing "%" in urlbar to find open tabs should still list tabs from hibernating groups.

If one tab from hibernating group is selected (loaded), then its group is no longer hibernating.

Relevant: groups without any loaded tab shouldn't be considered as hibernating group. The group only becomes a hibernating group after specific user action.

**Comment by wwp** [comment]
What you describe seems particularly complex to me. You could use an add-on like the auto tab discard, to "hibernate" tabs after a delay, which makes simple behaviours and allow whole tag groups to sleep.

**Comment by pintassilgo** [comment]
What I want has nothing to do with auto tab discard, I don't like that.

In fact, I think that what I want is very simple to implement.

In the hotkeys command functions to switch groups, just include something like:
```
if (groups[next].hibernating)
  continue; //skip
```

So that hibernating groups will not be selected via hotkeys.

Also, of course, a little code to provide the UI so the user can set a group as "in hibernation". And a `tabs.onActivated` listener (or something similar, I'm not familiar with WebExt API) to remove the hibernating state of a group if any of its tabs is loaded.

The only pending thing is if a group awaken from hibernation should back to hibernation state on browser restart. I think it should return to hibernation. Persistent hibernation status change should only occur by direct user action.

**Comment by joshyy1312** [comment]
The old tab groups had a very simple hibernate option.

Just right click on a group and set it to hibernate, it then would be moved in a separate menu and not appear in the group list anymore...

Quite simple and useful to keep recurrent groups stored and focus on the "currently active" ones.

I'd like this simple option back too :)

**Comment by Drive4ik** [comment]
In fact, I think that this is absolutely unnecessary functionality, since it does nothing but skip a group when switching groups using hot keys or in another way. At the same time, the functionality has a loud name "stash" or "hibernate". Which in its essence does not reflect its real functionality.
In fact, I had a thought, and somewhere there is a ticket for it, make a complete archiving of the group. That is, the tabs will be exactly closed, and the group is moved to the end of the list and becomes inactive. At the same time, all tabs (URLs) are stored in the add-on database, and not in the browser session. This will greatly facilitate the launch of the browser. Since there are users who have 30+ groups and in each 50+ tabs.
And launching a browser with a large number of tabs (even if they are not loaded right away) is very long.
I myself will really need this function, since I have groups that have 30+ tabs, I only use them from once every half a year, and they are in my memory every day, even if not loaded.
I’ve freed myself a bit now and will take care of this and other functionality.
I really hope you enjoy this option)

**Comment by okumam** [comment]
Just wanted to jump in and say that this is a great idea.  As I posted in another thread, I currently use the bookmarking feature to handle this-  backup a group that I want to put away into a bookmark folder, close the group and whenever I need it again, I create a group from the bookmark folder.  Your suggestion does this much faster I think.

By the way, is there a forum where users can talk about your addon, asking questions and posting tips?

**Comment by Drive4ik** [comment]
> By the way, is there a forum where users can talk about your addon, asking questions and posting tips?

@okumam Other than Github, there is nothing :)

**Comment by okumam** [comment]
If you think GitHub isn't a great place for general discussion, questions, tips and so on, I just created a subreddit on reddit:  https://www.reddit.com/r/SimpleTabGroups

If you think it's valuable, please let everyone know, so we can get some conversations going.  If you wish, I am happy to make you a moderator or owner or whatever you like.

**Comment by Drive4ik** [comment]
@okumam Cool! Thank you for that, but I don't think there's much to discuss. As far as I can see, so far, users have enough GitHub.
But thank you anyway!

**Comment by Drive4ik** [comment]
done
option will be here
![изображение](https://user-images.githubusercontent.com/7843031/74743881-de217600-5269-11ea-9930-827dc22c5613.png)
