### ISSUE TITLE
When switching to new group some of the tabs get deleted/lose their urls

### ISSUE THREAD

**Issue by 38cards** [Drive4ik/simple-tab-groups#52]
When switching to new group some of the tabs get deleted/lose their urls and you are unable to reload them, this only happens sometimes and I not sure what is causing it.

**Comment by SladeThe** [comment]
+

**Comment by soerpoers** [comment]
yeah, for me too. can’t expect why, looks like it reflects only the oldest tabs but i  can’t verify…

**Comment by DrTron** [comment]
Can confirm, happens to me, too. Not necessarily the oldest tabs, it rather seems random.

**Comment by Drive4ik** [comment]
@38cards @SladeThe @soerpoers @DrTron 
Hi guys
Perhaps your problem is related to this bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1435077
there is animation please see

if not, please tell me about your OS and how many tabs has group when switch to it?

P.S. if the newly opened tab is still loading - it is better not to switch the group until it is added there, otherwise there is a risk of losing it.
these are restrictions webextensions api.

**Comment by DrTron** [comment]
Doesn't seem to be the same bug.
- Tabs in question have been activated before.
- they don't vanish, but are replaced by an empty "New Tab".
OS: Win7 and Debian Linux with usually >10 Tabs in each of the five groups.
Currently running FF 58.0.1

**Comment by jsilence** [comment]
Same here. FF60 on Ubuntu 17.10.
Seven tab groups with mostly single digit number of tabs.

**Comment by Drive4ik** [comment]
Hi all. Can you check whether this issue replicate on the new version of the add-on STG v3.0.7 and FF 61?
If not, please close the bug
