### ISSUE TITLE
 "Always open tabs in container" behaviour is buggy.

### ISSUE THREAD

**Issue by avshyz** [Drive4ik/simple-tab-groups#529]
**Describe the bug**
When certain websites are marked as (from Multi Account Containers to always open in a certain container) are opened, and the current group is set to "Always open tabs in container" where the selected container is the same one - It will be opened twice.

The same happen when you right click on a tab attached to said container, and click on "reopen in container -> no container".

**To Reproduce**
1. Navigate to a site
2. Click on Multi Account Container's icon, set to "Always open in personal"
3. Open a new group in STG
4. In its' options, set it to "Always open tabs in container", and select the Personal container.

5. Switch to the newly created group, and open a tab. Notice how, even though, we've set STG to open new tabs in that group in the personal container - the new tab is in the default container
6. navigate to the site from 1. Notice how the tab is duplicated.

Moreover:
7. open a new tab, and navigate to a different site. After navigating, the tab will be moved from the default container to the personal container.
8. Navigate to the website from 1. Notice how when the container is the personal container - it won't duplicate.

**Expected behavior**
That tabs wouldn't be duplicated :)

**Desktop (please complete the following information):**
 - OS and version: osx 10.15.3
 - Firefox version: 72.0.2
 - Simple Tab Groups version: 6.1.1

**Additional context**
When you open a new tab, *even though* you have set the extension to "Always open tabs in container" - it'll be opened in the default container. 

This behavior happen *only* when you navigate to a website from a new tab.
If you were at a tab of the same container, when you navigate to the website - it won't be duplicated.

**Comment by avshyz** [comment]
Update - the same behavior happen when you use Facebook Container extension. (Even when "If the container is different from the selected one - change the container" is unmarked)
I fear as if every extension that forces tabs to open in a certain container, and said container is different than the one associated with that group, will cause the same issue.

**Comment by Drive4ik** [comment]
Hi! I understand what you are talking about, and I tried to get rid of this problem to the maximum. Since I do not have access to the data of other add-ons (and this is normal), I don’t know which addon does what. And since you use similar functionality in one add-on and in another add-on, there may be problems and duplicates.
In fact, my addon can replace most addons `Multi Account Containers` and `Facebook Container`.
You only need to specify the rules for opening and regexp. 
The same thing with `Facebook Container`, you can make a group for facebook, and set the container and regular expression for `facebook.com` and all the tabs will move there in the desired container.

**Comment by avshyz** [comment]
I see, that's understandable, and I do see how STG can replace these addons, but it's kinda workaround-y :)

Since it only happened when you try navigating from a new tab (which is always opened at the default container) - isn't there a way to make new tabs appear in the right account, before the navigation?

**Comment by Drive4ik** [comment]
The point is that when a tab is created, the code can see what addon it was created with. Or a user. And when I see that the rules of the tab imply its re-creation in another container, I also look at who created the tab. And if it's a different addon, then I cancel my action. Because it will cause one addon and another addon to open the tabs cyclically.
There is no such code in Multi Account Containers and Facebook Container addons, so 2 tabs are opened - one by my addon when the user clicks to open, and the other, for example, Facebook Container.

> Since it only happened when you try navigating from a new tab (which is always opened at the default container) - isn't there a way to make new tabs appear in the right account, before the navigation?

I'm working on my way around right now. I'm redoing the Create new tab addon plugin. The container will follow the active group. It'll look like this:
![firefox-follow-acive-group](https://user-images.githubusercontent.com/7843031/74344005-9eafe100-4db4-11ea-9bd6-21cf4e5c2004.gif)

**Comment by avshyz** [comment]
Sorry for the delay in my response, the notifications of this correspondence got to my spam!
Regardless - I now understand the issue.

The workaround looks great actually! It seems as if hiding the + icon (the default icon for creating new tabs) will solve this issue completely. Is it possible to make that icon open tabs in the default container if no container is set to this group?
Will it be possible to add a keyboard shortcut to open a tab in the group's container?!

**Comment by Drive4ik** [comment]
> Is it possible to make that icon open tabs in the default container if no container is set to this group?

Yeah, that's how the addon will work. If there's a container, we open it, and if not, we open it in the standard one.

> Will it be possible to add a keyboard shortcut to open a tab in the group's container?!

Yes, of course.

**Comment by avshyz** [comment]
Awesomesauce :)

**Comment by Drive4ik** [comment]
done, please wait next release.
and install/update addon https://addons.mozilla.org/firefox/addon/stg-plugin-create-new-tab/ 
now this plugin (v1.0) not support this functional, version 2.0 should support

**Comment by Ludomancer** [comment]
Found this bug after my comment on Facebook Container bug. Just in case this was not covered above. I'm seeing this with most up-to-date version from Firefox website.

Quoted from: https://github.com/Drive4ik/simple-tab-groups/issues/572
> 
> 
> I think I might be still seeing similar behavior.
> 
> Setup:
> My Default group is set to change the container to Personal.
> It is set to ignore Facebook Container all other containers except for the "no container" option.
> 
> ![image](https://user-images.githubusercontent.com/6220948/87336847-6b77a680-c53a-11ea-96d3-5b53903487b1.png)
> 
> Result:
> When I open "facebook.com", I believe Facebook Container and STG is conflicting and after bit of tabs openning closing erratically I end up having 2 tabs with "www.facebook.com" URL opened in Facebook Container.
> 
> ![image](https://user-images.githubusercontent.com/6220948/87336903-7d594980-c53a-11ea-97ec-b23f17d3d586.png)

**Comment by Drive4ik** [comment]
@Ludomancer I have fixed this bug. Wait for the next release
