### ISSUE TITLE
Switching groups with lots of tabs takes far too long

### ISSUE THREAD

**Issue by Illiou** [Drive4ik/simple-tab-groups#533]
When I switch to or from a group with a lot of tabs (1600 in this case) switching takes over 10 minutes while Firefox fills up my whole RAM. I mean, that's a lot of tabs but 99% of them are unloaded so I don't see how that would need to take that long.

What happens more specifically is that after I click a group to switch, the interface takes about 20 seconds to hide the tabs and show the tabs from the new group. In that time the RAM usage of one Firefox process shots up until my RAM is full and that process takes 11 GB. Then the interface is already fully responsive again (switch tabs, scroll etc.), but only loading a webpage or any AJAX on a page doesn't work. Then over the next 10 or more minutes STG show the loading icon and that Firefox process' RAM usage slowly drops in 50 MB steps until it is at 200 MB and STG suddenly finishes loading.

I'm not sure what it is doing in that time, but it seems to be solely the add-on which is still doing stuff since I can already view all the tabs etc. So I hope there is something to be improved significantly here.

Specs:
Windows 10
Firefox 73.0
Simple Tab Groups 4.3.6.2

I have attached the debug log of a group switch, maybe it has anything useful.
[STG-slow-group-change.zip](https://github.com/Drive4ik/simple-tab-groups/files/4204804/STG-slow-group-change.zip)

**Comment by Drive4ik** [comment]
Hey. I tried to optimize the band load speed, but still a lot depends on the browser. Because I can't increase the speed anymore... I also noticed that your browser has been running for over 14 hours. And like any program, FF can glitch if it hasn't rebooted for a long time. It's also important how much RAM your computer has. Either way, wait for version 4.4.2 or higher and check it out (it's currently under review).

**Comment by Illiou** [comment]
Well it seems I have found the culprit. Turns out this issue is caused by having another add-on called Mate Translate installed together with STG.

I had just a few days ago removed this add-on because I found that it massively slows down website loading speed. Yesterday I had noticed that switching the group would now suddenly happen within some seconds and I was just writting this answer here as it hit me and I remembered this um.. flawed add-on...

It seems this add-on is doing some kind of processing on all tabs within the browser, even the hidden and unloaded ones, every time you switch groups. I contacted the add-on developers and urged them to fix this terrible behavior.

Is there anything you can do from your side to prevent such behavior with other add-ons like this one installed or would you say this is entirely down to other add-on developer and/or Firefox?

**Comment by Drive4ik** [comment]
Unfortunately, I can't influence the other extensions in any way. 
This is not the first time this has happened, and this is not the only addon that conflicts with STG. In most cases addons are old, and do not take into account hidden tabs. I already have a blacklist of such addons, and I think I will soon give notification if the user has such addons installed. So that the user knows that they can slow down or block the STG.
Thank you for finding out what the problem was, and we wrote about it here.

**Comment by Illiou** [comment]
Having a notification for conflicting add-ons sounds a like really user-friendly addition! The only difficulty I can see is keeping it up to date when add-ons fix their behavior.

**Comment by Drive4ik** [comment]
Yes, I agree. It will also bind to the version of the addon, and will be shown to the user once at startup, until the user clicks on the notification and reads the conflicting addons.
