### ISSUE TITLE
[Feature Request] Remember active tab in closed group

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#561]
Would it be possible to make STG reopen a group/window with the same active tab as when it was closed, instead of defaulting to the first (leftmost) tab?

That'd certainly be a nice little addition.

**Comment by Drive4ik** [comment]
This is not possible for several reasons. For example, when you close a window, the tabs also close, and open in another window (hidden) and lose the value of the last active tab. Saving tab IDs also fails, since the tab IDs are recreated when you open the browser. If I still try to work around this, it will greatly complicate the logic and operation of the addon, and also affect the speed, since each time you click on the tab, you need to save data, and the load on the database increases ...
Unfortunately, this is not yet possible.
