### ISSUE TITLE
Create many duplicated tab in target group when drop one tab from source group to target group.

### ISSUE THREAD

**Issue by zw963** [Drive4ik/simple-tab-groups#563]
**Describe the bug**
When drag tab from one group(A) into another group(B)  when mouse hover on group B, occasionally, click wrong position,  make target group(B) all tab opened, in this case, can cause many tab duplicated from A to B

**Expected behavior**
Should not create many duplicated tab, which make maintain more difficult.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version:  Arch Linux
 - Firefox version:  compiled nightly, 75.0b3
 - Simple Tab Groups version:  4.4.2.5

**Additional context**
I have many tab was saved with in differnt group before several month ago, use more older version, since than, i never try to use plugin,  and today, i try to clean recently history use fire clean history feature, after i done, i found all tabs was gone,  so, i use another plugin: `tab session manager` restore all my tabs into 3 windows, and hundreds of tab, and all tabs is out of my old groups, yes, all group tab change to zero, so, i have to reassign tabs into different group, this issue happen on this case.

Thank you

**Comment by Drive4ik** [comment]
Hi!
The fact is that when tabs and windows are created, and STG works while doing this, it tries to assign a group to tabs or remove it from the session. Because the connection of the tab with the group is saved in the browser session.
I know about this problem, but still can not solve it.
I can advise you not to use session managers. If you enable session recovery in the browser, then it copes well with this task. Closing the browser when you click not on the cross, but on
![изображение](https://user-images.githubusercontent.com/7843031/77080232-bb69b500-6a01-11ea-8bd5-f0c3bc270386.png)
completely closes all browser windows and the browser itself. And when the browser opens again, it restores all windows and tabs. In this mode, the STG works without problems

**Comment by zw963** [comment]
> Closing the browser when you click not on the cross, but on completely closes all browser windows and the browser itself. 

Thank you for you advice.
