### ISSUE TITLE
Document different ways of managing keyboard shortcuts

### ISSUE THREAD

**Issue by jul1u5** [Drive4ik/simple-tab-groups#577]
**Is your feature request related to a problem? Please describe.**
Currently, there are two ways of defining keyboard shortcuts for the extension:
- "Hotkeys" tab in the STG Settings (can be accessed via the extension's popup)
- "Manage Extension Shortcuts" page from the Firefox Extensions page in [about:addons](about:addons).

**Describe the solution you'd like**
I would like to have some documentation on what are the differences between these two ways of managing the extension's keyboard shortcuts.

**Additional context**
STG Settings Hotkeys page:
![screenshot](https://user-images.githubusercontent.com/8469822/77862287-25b0ff80-7223-11ea-8013-6105ce7a0c48.png)
Manage Extension Shortcuts page:
![screenshot](https://user-images.githubusercontent.com/8469822/77862308-45e0be80-7223-11ea-8b29-af4274fc7fb9.png)

**Comment by iTeaMaster** [comment]
IMO there is no need to keep such a feature redundancy, we have the built-in shortcut settings from FF since nightly 66. It only confuses users, and thus rather than documenting it, this should be disabled entirely.

**Comment by jul1u5** [comment]
One thing to note here is that the STG Settings offer more functionality. For example, in the Hotkeys tab I can do stuff like this:
![image](https://user-images.githubusercontent.com/8469822/81055422-54309300-8ed1-11ea-82ad-8a89567e1304.png)

This is not possible in the built-in Firefox extension settings.

**Comment by iTeaMaster** [comment]
I see. Had not noticed this functionality before. Actually the 'load custom group' option is displayed in the firefox addon keyboard shortcut settings also, which currently doesn't make sense (it doesn't work). Either FF should support managing context (such as the dropdown for custom group selection) between extension and shortcut settings page, or the value shouldn't appear at all.
Still, imo the STG hotkeys setting menu should be reduced to the functionality that is not already in the FF options, if they are not synchronized.

However, now I see that this issue is completely valid and the functionality and situation need to be clearly documented. I shall elaborate my ideas mentioned above into sperate issues/feature requests.

**Comment by Drive4ik** [comment]
>  I would like to have some documentation on what are the differences between these two ways of managing the extension's keyboard shortcuts.

In fact, there are no differences; there are different possibilities.
In the addon settings you can assign hot keys very subtly, for each group, different keyboard shortcuts. But there are also disadvantages - these hot keys will not work on secure browser pages (`about:preferences`)

Configuring hotkeys through about:addons has less ability to assign different keys, and there is no group selection, but these hotkeys will work on all pages of the browser.

It all depends on the user and his desires.

I now will not redo the functionality of hot keys.

**Comment by jul1u5** [comment]
I still think it would be a good idea to reference the Manage Extension Shortcuts page in the Hotkeys tab. After seeing the Hotkeys tab, users might assume that's the only to add keyboard shortcuts.

**Comment by Drive4ik** [comment]
This is a good idea. I added an additional explanation
![изображение](https://user-images.githubusercontent.com/7843031/81207287-03ef2900-8fd6-11ea-9af7-cdd5ddbb4839.png)
