### ISSUE TITLE
Auto Backup is appending Firefox version to folder name

### ISSUE THREAD

**Issue by Tyrewt** [Drive4ik/simple-tab-groups#590]
STG 4.5 Auto Backup is appending Firefox version to folder name, eg: **STG-backups** has become **STG-backups-FF-75.0**

This is an issue because:

1. STG Auto backup does not have options to limit X number or X days of backups and will continually keep saving them day after day. I wrote a script to delete backups older than 14 days (my preference), but if the folder name changes (path), this breaks the script.

2. Upon each update the older folder and contents is left on the system, eg: STG-backups-FF-75.0, STG-backups-FF-74.0.1, STG-backups-FF-74.0. This is yet again more file system clutter.

The Folder name entered by the user needs to be enforced, otherwise we need some house keeping options to limit and clean-up old backups.

**Comment by Drive4ik** [comment]
The renaming of the folder was made specifically in order to distinguish between backups according to the FF version, because webextensions does not have the ability to delete files. This is done in connection with security.
Renaming a folder from STG-backups to STG-backups-FF-75.0 was done only once when switching to add-on version 4.5. You can change the name of the folder to STG-backups and everything will work as before.
Differentiation according to the FF version was made for convenience, so that the user can know what backups to restore to him in case of an unexpected error after updating FF.
So far there is no safe way to manage webextensions backups, so I have to get out like this.

**Comment by Tyrewt** [comment]
Understandable. So the folder change will not occur every time there is an update, if manually changed back to **STG-backups** this will stick?

**Comment by Drive4ik** [comment]
Yes, there will be no more automatic change of the folder name. If the folder will have the name STG-backups-FF-75.0, then the next update FF folder name will change.

**Comment by Tyrewt** [comment]
Thank you for all your work.
