### ISSUE TITLE
Add `Discard Tab` to right click option of tab (not in pop up)

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#617]
**Is your feature request related to a problem? Please describe.**
To discard a tab, now we need to open addon popup > select the tab group > scroll and find tab to be discarded > right click > `Discard Tab`. The process just somehow too complicate. Consider user just accidentially click wrong tab (e.g.: clicked the one just next to desired one) and want to discard it quickly, he/she must follow above processes. It is nightmare if user have many tabs in a group but just want to discard the middle one.

**Describe the solution you'd like**
Add the option to right click on Firefox tab and select `discard tab` just similar to the option `Move tab to group`. I don't mind if you want to put the option inside `Move tab to group`.

**Describe alternatives you've considered**
Other addon that can discard tab with right click option can co-work quite good with STG. But it is also not a bad idea if STG already included it.

**Comment by Drive4ik** [comment]
The addon has only one item for the context menu. And for STG, this is a folder for moving a tab to another group. The add-ons are actually made in order to enable the necessary functionality, and not to make a mega big add-on with all the functions)))
Try this
https://addons.mozilla.org/firefox/addon/discard-tab/
