### ISSUE TITLE
Does Simple Tab Groups enable containers?

### ISSUE THREAD

**Issue by chileverde** [Drive4ik/simple-tab-groups#643]
All the articles I have seen about using containers in Firefox say I must add an extension for containers, such as Firefox Multi-Account Containers, in order to use them.

I have not added any container extension, but when I right-click on a tab, there is an option to Reopen in Container. I discovered that I can already use containers. In Firefox Options, in the area on Tabs, there is a note: "An extension, Simple Tab Groups, requires Container Tabs." Below that, there is a grayed-out line with a checked box (that cannot be unchecked) saying "Enable Container Tabs". To the right, I can click on Settings... and manage my containers, including creating new ones.

Did Simple Tab Groups enable containers when I installed it? Looks like I can use containers without installing another extension. That's great! You should add this to the description of Simple Tab Groups so people know it will make containers available without their needing to install another extension. (Or if there is a reason I should install Firefox Multi-Account Containers, please let me know.)

**Comment by MrQwerky** [comment]
I have both "Multi-Account Containers" and "Simple Tab Groups" installed.  Then I installed "Cookie Quick Manager".  Now, in Firefox Options, I see (like you) "An extension, ... , requires Container Tabs."  But in my case, the named extension is "Cookie Quick Manager".  As this was the last of the three I installed, it would seem that Firefox Options just names the last installed container-using extension.  So what you read about using containers does require some container-using extension to be installed, may very well be true.  "Simple Tab Groups", since it allows Temporary Containers, is one such extension.

The "Multi-Account Containers" extension icon, when clicked, provides exactly the same options as the Firefox "Settings" button at the "Enable Container Tabs" checkbox in Options.  So as far as I can tell now, the only advantage to having "Multi-Account Containers" installed, is that it makes it very much easier to edit your container settings, without having to go to Firefox Options.

**Comment by chileverde** [comment]
MrQwerky,

Thanks so much.

I am trying not to use more extensions than I really need, so I will keep my current set up. Still, it is good to know the advantage of adding "Multi-Account Containers". Maybe I'll try it in the future.

chileverde
