### ISSUE TITLE
There's no way to dismiss this alert forever (And it interferes with VimiumC)

### ISSUE THREAD

**Issue by Zeioth** [Drive4ik/simple-tab-groups#655]
Problem:
There's no way to dismiss the alert forever.

**How to reproduce:**

   
-  Install the plugins 'VimiumC' and 'Simple tab groups'.
-  Create a tab group and select it.
-  On any website, press the key 'B', write some text to search a marker, and press ctrl+shift+enter to open it in a new tab.

Everytime you do it, you'll see the next window.
![Captura de pantalla_2020-07-18_17-01-50](https://user-images.githubusercontent.com/3357792/87855536-51164200-c919-11ea-82c7-8fc8fe302608.png)

**What should happen**: Give the user an option to remember the selection, and don't show the page again.

**Related links:** 

- https://github.com/gdh1995/vimium-c/issues/198
- https://www.reddit.com/r/firefox/comments/hti0po/theres_some_way_to_auto_accept_forever_this_see

**Comment by Zeioth** [comment]
Confirmed, this is an issue of simple tab groups:
https://github.com/gdh1995/vimium-c/issues/198#issuecomment-664474008

**Comment by Drive4ik** [comment]
I cannot change this behavior because it will break the logic for working with other addons, for example "Firefox Multi-Account Containers", "Facebook Container", "Google Container" etc.

The only solution I see is to open a new tab with the container from the current tab with the addon. This is how opening links works, for example. If you are in the "Personal" container and open the link with the middle mouse button (in a new window), then this new tab has a parent tab container.
This change needs to be done in the VimiumC addon

**Comment by Zeioth** [comment]
It's been fixed by vimium-c, the issue can be closed. Thank you!
