### ISSUE TITLE
Feat Req: Sort Tabs Within Groups

### ISSUE THREAD

**Issue by jeremymeyers** [Drive4ik/simple-tab-groups#672]
It would be great to be able to programmatically sort the tabs within the group.

Suggested sorting options:
- Alphabetically by page title
- By Domain (to keep all youtube tabs together, for example)
- By Age (i.e. date the tab was open)

**Comment by Drive4ik** [comment]
The introduction of this functionality is not planned due to the fact that other add-ons can do it. Just find a suitable addon for yourself, for example 
https://addons.mozilla.org/en-US/firefox/addon/sort-tabs-advanced/

or from this list
https://addons.mozilla.org/en-US/firefox/search/?q=sort+tabs
