### ISSUE TITLE
KB Shortcuts for re-ordering groups (and tabs) within STG.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#690]
**Is your feature request related to a problem? Please describe.**
When I create a new group, I have to drag it to the top, then wait for the scrollbar to focus it in the centre, then drag it to the top again, repeating this around 5-10x over half a minute.

**Describe the solution you'd like**
Keyboard shortcut to move the selected group (in sidebar, in the group list). Ctrl+Shift+PgUp/Dn moves tabs in the browser, while STG is selected, the same kb shortcuts should apply.

**Additional context**
Tabs within the group list could also inherit the behaviour.

**Comment by Drive4ik** [comment]
There are some problems:
moving groups - how to find out which group to drag, if you need to drag a non-current (loaded) group. Focusing on a group is a bad idea because the group will load immediately.
moving tabs - speed problems are also possible. If you press and hold `Ctrl + Shift + PageUp / Down` then you need to repeat the same operation to move the tabs several times with an interval of ~ 5ms. It is very fast, and bugs are possible, since the work is done with the browser API and there you need to wait for the action to end.

It's a good idea, but I won't take it on yet.

**Comment by jtagcat** [comment]
Any other hack patches to move groups in the list? It takes literally 20-30s to re-order _a_ group, not even mentioning multiple.
