### ISSUE TITLE
STG not restorning tabs nor is Toolbar folder being created. 

### ISSUE THREAD

**Issue by dbidle** [Drive4ik/simple-tab-groups#692]
New MacBook Pro running Catalina with FF 81.0.2 with STG installed. I have ran though all the settings and compared with my Windows 10 computer running same version of FF and the Mac will not restore tabs. I noticed that the STG bookmarks folder is not being created in Bookmarks Toolbar either and every time I reopen FF the tabs will not restore. I checked that restore previous session is checked marked as well. This is a fresh install of FF and just updated from 81.0.1 and it was not working on that patch as well. 

macOS Catalina: 10.15.7
FF: 81.0.2
STG: 4.5.2

**Comment by dbidle** [comment]
Update: was able to get STG bookmarks created automatically by the auto backup but tabs are still not restoring on restart.

**Comment by Drive4ik** [comment]
Yes, there is such a problem on Linux systems. And so far I cannot solve it. This is due to the fact that closing the browser does not end the browser process as well as the addon process.
I can advise you to close the browser using the hamburger menu or `Ctrl+Shift+Q`

![изображение](https://user-images.githubusercontent.com/7843031/96177965-62caae00-0f37-11eb-8e28-093d4339d3f6.png)

**Comment by dbidle** [comment]
Great to know, thanks so much!
