### ISSUE TITLE
Tree-style Tab and STG archiving: restoring also icons and tree status (expanded/collapsed)

### ISSUE THREAD

**Issue by byblo** [Drive4ik/simple-tab-groups#708]
Since STG 4.5.5, archiving and restoring while using TST seems working well. Thank you for this!

This said, the tree status is not fully restored: All the trees are expanded when restored, including ones that were collapsed before archiving.

Icons are also missing after restoring archived group.

**Comment by Drive4ik** [comment]
Group archiving is the complete closure of tabs in the browser.
Group unarchiving is creating tabs from scratch with the `discarded` parameter, which means that a tab will not load until it is activated, and since it does not load, we do not know what icon it has. 
For the same reasons, the state of the tree (expanded/collapsed) cannot be saved. I don't think it is that important.
