### ISSUE TITLE
Switching Between groups with many tabs, scrolls the focused tab out of view 

### ISSUE THREAD

**Issue by StoopidoMan** [Drive4ik/simple-tab-groups#714]
**Describe the bug**
When switching to a group with many tabs (100+) the focused tab is out of view in the "Tab bar", hard to explain, here is a screenshot of the tab I was on when I switch to this group:
![image](https://user-images.githubusercontent.com/71223069/98372317-fbe07680-2056-11eb-876f-beeaee6843ca.png)

Here is the "Tab Bar":
![image](https://user-images.githubusercontent.com/71223069/98372491-48c44d00-2057-11eb-8cf3-5fb731a17444.png)

The issue ruins the experience because I have to scroll around, or search for that active tab:
![image](https://user-images.githubusercontent.com/71223069/98372555-61346780-2057-11eb-9cf3-82e06dd43b9c.png)

**To Reproduce**
1. On a new profile, make many tabs till it is scroll-able and then add another 20 tabs just for fun. 
2. Switch to a different group
3. Then switch back to that group.
4. See, that you have to scroll the "Tab Bar" (not sure what it is called) to find the Focused on Tab or Active tab

**Expected behavior**
When I switch to a group, I want to see on the "Tab bar" the selected/active/focused on tab, this way I don't have to search for that tab 

**Desktop (please complete the following information):**
 - OS and version: Windows 
 - Firefox version: 82.0.2
 - Simple Tab Groups version: 4.5.5.1

PS: not related to this issue, just for you to note. Loading a tab group with 600+ tabs (a test profile) is not elegant and looks weird, the tabs disappears one by one and then reapers. I think this is a limitation of "Tab hide" API, I wish if it was elegant as how it was with Pre-webexteion Firefox 

Thank you,
Love your STG :)

**Comment by Drive4ik** [comment]
Yes, I know this behavior. Sometimes it happens. But unfortunately I cannot influence this in any way, because there is no API for this, the browser itself controls this...

**Comment by StoopidoMan** [comment]
Well, it is possible with other add-ons, you can check their code or ask the developer. For example All Tabs Helper side bar, I search for the tabs even if it is hidden, and it will take me to that tabs and it will be shown in the tab bar:  but with STG search and tab switching sometimes this doesn't happens, meaning, I will be on that tab, but not on "tab bar"

if you don't understand, I can send you a GIF using both addons to switch to a group or a tab.

**Comment by StoopidoMan** [comment]
I did a test using All Tab Helper:

GIF:
![p9eDRhN6Qs](https://user-images.githubusercontent.com/71223069/98441898-c1d8a880-211a-11eb-854a-973430f2c762.gif)

I was on a small group of five tabs, and then switch to a large group by searching for a tab of a google search for "Somewhere in middle of many many tabs"  and it worked! many times, but with STG sometimes it doesn't work, that why I either use builting search of STG again or ALL Tab helper to find where is the tab that i am on: 

I think it might be "calling  tab "  API that is used by add-ons that searches for tabs,  so maybe using that API after you switch to a tab to scroll the tab bar to that active Tab.  

And if this is solution maybe do a research to see if you can scroll the tab to the middle of the screen or at right corner of the tab bar

Middle of the screen:
![image](https://user-images.githubusercontent.com/71223069/98441739-ade07700-2119-11eb-9c90-b9395a17926c.png)

Or at right corner:
![image](https://user-images.githubusercontent.com/71223069/98441748-c6509180-2119-11eb-81f0-d14f34ae9b97.png)

**Comment by StoopidoMan** [comment]
@Drive4ik , if you want me to do any test let me know, as I said ATH does it without and works all the times

**Comment by Drive4ik** [comment]
So.
All Tabs Helper does not have the ability (like STG) to scroll.
All it does on your GIF is to activate the tab. If you noticed, then the group of tabs changes. Here's the whole chain of events:
ATH makes the tab active
STG notices this, and also notices that this tab was hidden before.
STG sees that the tab belongs to another group (which is not currently loaded), which means that the tab got out of the group at the request of the user - you.
STG loads the group into the current window with the same active tab.
And you see what you see.
ATH has nothing to do with it.

Now, I found out why this is happening.
How does the group switch now?
New group tabs are shown
the desired group tab is made active
old group tabs are hidden

So, if a tab is active, it cannot be hidden.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide

Therefore, such a chain of events. And scrolling breaks down at the step of hiding the tabs of the old group. That is, the browser scrolls everything correctly, to the active tab. But as soon as the tabs of the old group are hidden, the browser immediately changes the scroll to the end of all tabs. I don't understand the reason, but I know for sure that this is an FF bug, since at this moment the tabs are hidden, and none of them are active, and scrolling should not be involved at all.

But because of your persistence, I once again revised the logic of switching groups. For the umpteenth time since the beginning of the development of the addon ...

How did I redo switching groups?
New group tabs are shown
old group tabs are hidden (except for the active one)
the desired group tab is made active
the active tab of the old group is hidden

How did you manage to defeat this problem, and a few more small ones))
And also the groups began to switch faster.

You can see the commit: b57aecaa11f7381a461b0387cd7cbfed5766d620

P.S. sorry for my English

**Comment by StoopidoMan** [comment]
I updated STG and tested it many times, this is the result I got: Now when I switch to  a group the active tab of that group is visible on the tab bar which is great! But the location was random, either on far right or left of the tab bar. This can be fixed  and I know there is no way for add-ons to control the position of tab bar scroll.  

And, thanks for the detailed insight of how it works, this helped me visualize what was/is going on. Having said that, I am not a programmer, so let me see if I understood how it works now:

when switching from **group A** to  **group B** :

1-  STG will hide all the tabs in **group A** then un-hide all the tabs of **Group B**.

2- Switch the Active tab from **group A** to **group B** Active tab (because web-extension don't give the option to hide active tab, I assume for security).

3- Hide **group A** active tab. 

And I THINK because the switching to **group B** active tab  happens after loading all the hidden tabs the active tab shows in the tab bar on left or right.

So after I noticed the position is either on left or right, I recorded my screen and watched it in reduced playback speed, and I think I know why the position of the tab is either on the far left side or the right side of the tab bar, here is how it goes:


>2- Switch the Active tab from **group A** to **group B** Active tab (because web-extension don't give the option to hide active tab, I assume for security).

Before step two [2-] if the Active tab of **Group A** is at the end the tab bar then when STG switch to **Group B** active tab the position of that tab goes to far right, and if it was at start of the tab bar then it goes to far left. 

thus, controlling the position of where **Group A** active tab would be will control where on the Tab bar **Group B** active tab will show. And I suggest to always show **Group B**  or [switch to group] active tab on far left because English and most languages start from left to right. Additionally, Firefox open new tabs/links on pages on the right side, thus you have a view of where you stopped your online research or project etc. :
![image](https://user-images.githubusercontent.com/71223069/98563790-09029d00-22c5-11eb-9a09-dde144a23144.png)


This may take additional effort to code, I am not sure how much, but I feel it is not that hard, but no matter what, it is crucial to implement this, here is are the reasons to make my case: 

1-first and foremost, every application must have a consistence user experience, hence,  STG should have a consistence behavior when switching between groups to improve user experience: 
2- users  will always know where the active tab will be on the screen (on the left side of the tab bar) hence their eyes will look there waiting every time for the switching of groups to finish. 
3- It feels uneasy to me and I believe all other users to  have the active tab of the group either on far left or right.
4- it makes new users of STG think that this behavior is caused by poor code or is a bug, hence leading them to uninstall STG and hurt it growth, I honestly believe that. 


Lastly, developers like you should voice their concern to Mozilla team, switching groups with STG is not as smooth as the old tab group add-on.  you see tab dancing around, it looks messy, and takes a lot of time with large groups. Maybe they could implement an API to group tabs together and hide/unhide them together, or improve on their work on the hide/unhide API 



PS: Sorry for my English too

Thank you for your hard work, I see why STG is recommended by Mozilla  :)  :+1:
