### ISSUE TITLE
Hotkeys not working in reader mode

### ISSUE THREAD

**Issue by Bareus** [Drive4ik/simple-tab-groups#732]
**Describe the bug**
When using reader mode on a page the hotkeys are not working anymore

**To Reproduce**
1. Go to a page which supports reader mode
2. Aktivate reader mode
3. Try to use one of the configured hotkeys (e.g. Ctrl + \` to switch to next group)

**Expected behavior**
Hotkeys are working

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox version: 82.0.3 (64bit)
 - Simple Tab Groups version: 4.6.2

**Comment by slysherz** [comment]
This happens with most (all?) firefox generated pages:
- Customize page
- Preferences
- Firefox Home

It only happens if the page is in focus - if you open one of these problematic pages, click on another tab and leave the problematic tab open, it works fine. Manually clicking on a different group also works fine, the only thing that doesn't work is the shortcut.

Thanks to the author for developing the extension, I found it recently and it's amazing!

**Comment by forgedhallpass** [comment]
The shortcuts are not working when an empty "_New Tab_" is in focus, or any tabs that relate to add-ons (e.g. STG settings tab, OneTab etc)...but I assume this also falls under the "_firefox generated pages_" mentioned by @slysherz

**Comment by Drive4ik** [comment]
You need to use this:

![изображение](https://user-images.githubusercontent.com/7843031/141006899-78b3ec0f-47cf-4ca5-9b88-0337adce4ddf.png)

https://support.mozilla.org/kb/manage-extension-shortcuts-firefox

**Comment by forgedhallpass** [comment]
@Drive4ik thanks for the answer, though it seems Firefox only permits using **word** characters for extension hotkeys, hence CTRL+` is not accepted. Do you happen to know a workaround for that?

**Comment by Drive4ik** [comment]
@forgedhallpass That's why I haven't removed the "Hotkeys" tab from the addon settings yet. But I do not know a workaround. I myself use `Ctrl+,` and `Ctrl+.`

**Comment by forgedhallpass** [comment]
I see. Thank you.
