### ISSUE TITLE
Handling tab-groups in the tab-bar.

### ISSUE THREAD

**Issue by LichenSymbiont** [Drive4ik/simple-tab-groups#739]
The most intuitive way to create tab groups would be to drag-and-drop tabs in the tab-bar.

So freely combining tab-groups and tabs in the tab bar, instead of a separate list interface.

I see two ways this may be implemented (if either is even possible, I don't know):

1. Make the tab-group "tab" open a list of tabs when you click it, and you can handle each item as a normal tab.
2. Make a tab-group "tab" push in its containing tabs to the right of it when clicked, and hide them when clicked again.

As it works right now, I seldom use this addon, sadly. I'd like to organize my browsing better, but I just don't find it intuitive enough.
Addendum: I might just be dumb for forgetting to use it ^^

**Comment by mjk-gh** [comment]
[Tab Groups Manager](https://www.ghacks.net/2014/03/21/tabgroups-manager-displays-firefox-tab-groups-frontend/) handled it like the first possibility you mentioned.
Although it worked, it was too cumbersome to work with, since it consisted
only of a tabgroup bar with just a single row of tab groups. This is fine for
just 3-5 groups, but if you use more, it's not the most efficient way to handle
this.

I propose that *if* it gets implemented this way, it should implement a multi-row
tab group bar, just like the [Paxmod](https://github.com/numirias/paxmod) addon does for the normal tab bar.

And I would suggest that the possibility to work with a vertical list of tab groups
should not be removed.

**Comment by LichenSymbiont** [comment]
Yes, I see your point. I don't quite agree with multi-row though, as I'd prefer to not take up more vertical space. Would be cool to try though! :)
So it would be best if you are limited to just a few tab-groups in this imaginary system.
So perhaps instead of switching between tab-groups, you could call in a tab-group to your tab-bar (so a single session -- no switching). And then freely closing tab-groups just like tabs, but having them saved, so you can call them up from a list-widget.

This way one could imagine another grouping system, where you switch between sessions of tabs and tab-groups.

But the basic idea is to have just one intuitive interface for tabs and tab-groups. Sure, tree-style-tabs does this, but I don't like to have it in a side-panel.

**Comment by Newbiez** [comment]
I have implemented a tabgroup toolbar for this addon based on an experimental toolbar API. But currently this is only working at developer edition and nightly and not on official firefox releases. As long Mozilla doesnt support us with a official toolbar API there is no chance to bring this ahead. We are waiting since 5 years now for Bug [1215064 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1215064), also the lot of votes seems not to be any kind of motivation for Mozilla to give them more priority.

@mjk-gh :
From the old TGM it was no problem to have 15 groups in the group bar and still to have 30% free space dependently how long the group name was. It would also be not my intention to spend more vertical space for a multirow group bar. I think the 1st 15-20 groups would be more as enough all other is findable in the STG menu.

**Comment by grahamperrin** [comment]
> … As long Mozilla doesnt support us with a official toolbar API there is no chance to bring this ahead. …

I'm not a developer, but I believe this. I'm one of the hundreds of voters for bug 1215064.  

In the absence of an API, I place _Bookmarks Toolbar Items_ in the menu bar (to the right of **File** and other menus). This can leave the Bookmarks toolbar free, to be used for extensions …

… but probably not free enough for the type of bar work that's desirable in this enhancement request #739.

**Comment by georg-eckert-zeiss** [comment]
This would make it a perfect alternative to Vivaldi's "Stacked Tabs".

**Comment by cmalard** [comment]
Some inspiration from Chrome:
[![](https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Chrome_Tab-Groups_In-Line-Image-v7.gif)](https://blog.google/products/chrome/manage-tabs-with-google-chrome/)

**Comment by Drive4ik** [comment]
Hi. This all became impossible after FF moved to version 57+. it was all there before, but the developers used this functionality irrationally. It turned out like this:
![](http://www.freecomputermaintenance.com/wp-content/uploads/2012/07/firefox-toolbars.jpg)

And it spoils the appearance of the browser. So we won't see it again, at least not without interfering with the browser core.
