### ISSUE TITLE
Backups are too large.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#758]
**Is your feature request related to a problem? Please describe.**
Even with all of 'include x in backups', a month of hourly backups is a GiB or so. This is fine by me, as I already made a script to offload older backups off-site.
This though might become problematic, when backups go more frequent than hourly. I've been planning to do one every 10 minutes, or even 5.

**Describe the solution you'd like**
Diffs for backups within the larger unit of interval. Current intervals available: daily/hourly.
If hourly backups, make one full backup daily, the next ones being diffs. If using daily, full backup weekly (or cap min interval of full backup to daily).

**Describe alternatives you've considered**
I mean I could do that with scripts, plus added compression, but that would only benefit me.

**Comment by grahamperrin** [comment]
> Diffs

Is this possible within the constraints of WebExtensions API?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions

**Comment by jtagcat** [comment]
jfyi for anyone looking for a solution, deduplicated fs is a thing.

**Comment by nekohayo** [comment]
If you'd like to implement (de)compression maybe the author would be happy to receive a merge request for it. Even with zip compression (rather than 7z/lzma/xz etc.) it reduces the filesize by roughly 80% (down to 21.5% of the original filesize). XZ compression brings it down further to 17.8% of the original size, but if this is significantly more complex to implement (?) then that sounds like overengineering to me.

Alternatively, maybe "automatically delete backup files older than 1 month" could be an option, if the webextensions API even allows that (?)

Personally, I don't see why you would need/want more than hourly backups though (I used to have them daily only, and have now switched to "every 5 hours" because I'm paranoid, but beyond that, I don't see a high likelihood of data loss, personally).

For me, a whole months of every-five-hours backups weighs 42 megabytes (note that my backups do not include thumbnails and favicons; I don't see why anyone would care about that in auto backups). So on my end, the filesizes are hardly a problem at all. It seems to me like your problem is more of a corner case that few users encounter in practice, so unless someone proposes a merge request for it, I doubt it'd be a priority for the maintainer...

**Comment by grahamperrin** [comment]
Thank you, 

> … maybe "automatically delete backup files older than 1 month" …

▶ https://github.com/Drive4ik/simple-tab-groups/issues/506#issuecomment-572841882

**Comment by Drive4ik** [comment]
@nekohayo 
> Alternatively, maybe "automatically delete backup files older than 1 month" could be an option, if the webextensions API even allows that (?)

There is no such thing. No direct access to the disk. Not anymore. It's too insecure. FF restriction.
