### ISSUE TITLE
Feature request: An confirmation if you click on the 2 sort groups options in the right click context menu

### ISSUE THREAD

**Issue by ufkhf** [Drive4ik/simple-tab-groups#818]

**Comment by nekohayo** [comment]
Hm, why would you need an extra confirmation for this? Those are deliberate actions that you really kind of have to explicitly look for to click on them... I've never hit those by mistake (and yet I use them every day or two). That said, if you want to eliminate the _chances_ of hitting them by mistake, I think the more straightforward way would be to have separator widgets before (and after) those two menu entries group, rather than bugging the user with yet another confirmation dialog (it would also be easier to implement for whoever might be attempting this).

**Comment by ufkhf** [comment]
Because if you have many groups in a particular order you're fucked. The only thing you can do is restore a backup which hopefully isn't too outdated. The "Sort groups" buttons are right above the discard group button, which make the chance of hitting to buttons very high. Also sometimes you just accidentally press the wrong mouse buttons and then you're also fucked, the buttons being located at the top makes this worse. They are very close to the mouse pointer. You can add separator widgets, but its still a good idea to add the confirmation dialog.


""Those are deliberate actions that you really kind of have to explicitly look for to click on them.''
They are literately at the TOP. 1 or 2 accidental mouse clicks and you're fucked

**Comment by Drive4ik** [comment]
@ufkhf  Don't swear. I understand you very well. I have a better idea: I will make an editor for the context menu of groups and tabs. In the settings will be a list of all the options for groups and tabs, and next to them will be "checkboxes", remove the checkbox - the item in the context menu will not show.

**Comment by Drive4ik** [comment]
please wait next release
@ufkhf And also, if you do not like the addon, or you have problems with coordination - do not write about it here, it's not cultural. If you want - do not use this addon. I put my heart into this addon, and I do it for free for everyone, including you. For this reason, I will not tolerate this kind of statements here.

![изображение](https://user-images.githubusercontent.com/7843031/142920733-eb034521-f11e-4dfa-bf00-bce2e11aadd6.png)
