### ISSUE TITLE
No longer works with FF 89.0 (64-bit)

### ISSUE THREAD

**Issue by helpfulBrother** [Drive4ik/simple-tab-groups#820]
The menu is no longer displayed for tabs that are on other groups.

Everything not in the current group is consolidated to a 'hidden' group, although grouping has been maintained when one of those tabs is selected.

**Comment by sebekhtc** [comment]
Same here, please update!

**Comment by tonywoode** [comment]
Perhaps it could help if you change the title of this issue, and explain the issue in a bit more detail. Personally I can't find anything that 'no longer works', so you mean a particular use case does not work rather that the plugin itself is critically broken - and personally I'm struggling to understand what your use case is (its possibly because I don't use STG in the same way as you?): if I go to 'manage groups' and right click on a tab from another group, and for me on macos catalina on FF 89, the menu appears....and if I use the STG icon, select the number of tabs next to a group to drop the tabs list down, and right click on one the tabs, the menu also appears.

**Comment by helpfulBrother** [comment]
Sorry, I thought this would be a widespread issue and that everyone would be experiencing it.
Basically the extension icon disappeared, so the only way to access the tab groups was using the chevron on the top menu.

Today I can see it again so life is good :D

Again apologies for the lack of info and thanks for the work on this very useful extension 👍 

![image](https://user-images.githubusercontent.com/44999712/120944543-6c2fb180-c778-11eb-963d-b7a21f340e82.png)
