### ISSUE TITLE
group.catchTabContainers is undefined

### ISSUE THREAD

**Issue by BogudanPro** [Drive4ik/simple-tab-groups#826]
**Describe the bug**
Extension says there is an errors...

**Desktop (please complete the following information):**
 - OS and version: Windows 7
 - Firefox version: 89.0.1
 - Simple Tab Groups version: 4.7

Attaching log file.

**Comment by BogudanPro** [comment]
Attaching didn't go as planned :(

https://pastebin.com/4chCKhU2

**Comment by BogudanPro** [comment]
Additional info: looks like issue source somewhere in the import from old Tab groups extension's backup, because STG begins reporting errors right after this action. Reload of extension and/or browser does not help.

**Comment by DeepMac** [comment]
- Confirmed this bug occurs when importing a backup from Quicksaver's Tab Groups.
- Confirmed it occurs if backup was made with, or without, the "Backup session data" option from Quicksaver's Tab Groups.
- Tabs from backup are created, but groups are not (assuming due to crash in STG extension)
- Deleting the STG extension completely and re-installing clears the error. Imported tabs remain.

**Comment by DeepMac** [comment]
All testing was done with a fresh profile that had no tab groups defined and only one tab open.

Creating even just one tab group seems to resolve this issue. After creating a test group, I was able to successfully run import with no error. All tabs and groups restored and persist properly on browser restart.

Error is somewhere in initialization process, likely triggered to an unexpected state after import.

**Comment by Drive4ik** [comment]
fixed d5710d6f429003ae568f3f13a7fba817808c2293
