### ISSUE TITLE
with many tabs/groups, usually have to reload tabs

### ISSUE THREAD

**Issue by dchmelik** [Drive4ik/simple-tab-groups#932]
I have 100+ tabs across six groups.  If I load one group's tabs, then another & another or all, by the time I get back to the first, some/all tabs no longer are loaded, so must be reloaded, unlike Firefox's original tab groups they'd stay loaded (also the way Pale Moon fork of Firefox does it.)

**To Reproduce**
1. Go to a tab group.
2. Select a window then all tabs in the group.
3. Go to another tab group, all tabs, and another, all tabs, and so on, until you're back to the first.
4. See error.

**Expected behavior**
Leave tabs loaded as long as users want them loaded, even indefinitely, at least option (even if takes more RAM.)

**Desktop (please complete the following information):**
 - OS and version: Slackware64 GNU/Linux 15.1+current
 - Firefox version: 97.0.1
 - Simple Tab Groups version: 4.2.7.1

**Comment by nekohayo** [comment]
You have not turned on the "Discard tabs after hide" option in the STG preferences, by any chance?

Otherwise, I think this would be Firefox itself doing that; [since version 93](https://hacks.mozilla.org/2021/10/tab-unloading-in-firefox-93/), Firefox now automatically unload idle tabs after a while, so if that's the case that's not STG's fault. You can see what firefox is doing by going to `about:unloads`.

**Comment by dchmelik** [comment]
No, I didn't turn that on.  I guess I won't use Firefox then.

**Comment by nekohayo** [comment]
If the issue is that Firefox itself is unloading your tabs because it feels like there's not enough RAM available (see if that's the case with `about:unloads`), you can probably change that behavior in `about:config` by flipping `browser.tabs.unloadOnLowMemory` to "false".
