### ISSUE TITLE
Slow as a turtle - crashed my computer

### ISSUE THREAD

**Issue by dlobaw** [Drive4ik/simple-tab-groups#97]
Installed Simple Tab Groups on Firefox 59.ob10. I created four groups. When switching between groups it took over 10 minutes to load and actually crashed the computer. I cannot figure out what happened, this extension must work properly or it would not exist. Any ideas???

**Comment by Drive4ik** [comment]
Are you sure that the browser plug-in could do this?
how many tabs were opened at the time of the bug?
What OS?
what exactly did you do at the time of the bug (opening tabs, can the video look)?
FF had problems with hardware acceleration in previous versions, because of which the whole system is hung, maybe this is the problem

**Comment by fgghjjkll** [comment]
I know WebExtensions work in a fundamentally different way than Firefox's original Tab Groups, and Quicksaver's implementation of it, but going from a tab group of 3000+ tabs that loaded fairly quickly on ff56 because only active tabs are loaded, to ff59 where STG attempts to load all 3000+ tabs does cause it to suck up all the RAM available and slow the system down to a crawl. I'm not entirely sure if this is able to be resolved due to architectural differences, but it would be interesting to hear about it from the perspective of a developer.

**Comment by Drive4ik** [comment]
Hi! You can use STG 3.0 and FF 61. There was implemented hide tabs api and tabs not reload after change group
