### ISSUE TITLE
All tab groups lost settings

### ISSUE THREAD

**Issue by JKinzer88** [Drive4ik/simple-tab-groups#991]
I closed firefox, as the memory usage was getting larged, and re-opened and every tab group i had setup no longer had any of the saved addresses i had associated with them.

**Comment by influential-eliot** [comment]
I'm wildly pontificating here, @JKinzer88, but I suspect that there's a tiny chance that whatever background functionality that's causing your issue is either the same as, or related to, what's causing the issue I raised in that [re-opened STG do not reopen in their Multi-Account Container](https://github.com/Drive4ik/simple-tab-groups/issues/990).

**Comment by Drive4ik** [comment]
Reopen the issue if the problem reappears. I can't reproduce it.
